import CapnProto
import CapnProtoCompiler
import CapnProtoConformance
import CapnProtoSchema
import Foundation
import Testing

@Test func emitsDeterministicRequestedFilesNestedScopesAndEscapedNames() throws {
    let request = try loadRequest("codegen-request")
    let first = try SwiftGenerator().generate(request)
    let second = try SwiftGenerator().generate(request)
    #expect(first == second)
    #expect(first.map(\.path) == ["keywords.capnp.swift", "import-user.capnp.swift"])

    let keywords = try #require(first.first?.contents)
    #expect(keywords.contains("public enum `Any`"))
    #expect(keywords.contains("    public enum `Protocol`"))
    #expect(keywords.contains("public struct `Type`"))
    #expect(!first.map(\.path).contains("import-base.capnp.swift"))
}

@Test(arguments: ["actor", "protocol", "extension", "repeat", "ordinaryName"])
func identifierEscaping(_ name: String) {
    let result = swiftIdentifier(name)
    #expect(result == (name == "ordinaryName" ? name : "`\(name)`"))
}

private func loadRequest(_ name: String) throws -> Schema.CodeGeneratorRequest {
    let url = try #require(
        Bundle.module.url(
            forResource: name, withExtension: "bin", subdirectory: "Fixtures"))
    return try Schema.CodeGeneratorRequest(framedBytes: Array(try Data(contentsOf: url)))
}

@Test func generatedReadersAndBuildersCoverValuesDefaultsListsAndUnknownEnums() throws {
    let message = try MessageBuilder()
    let builder = try TestAllTypes.initRoot(in: message)
    try builder.setBoolField(true)
    try builder.setInt8Field(-8)
    try builder.setInt16Field(-16)
    try builder.setInt32Field(-123_456)
    try builder.setInt64Field(-64)
    try builder.setUInt8Field(8)
    try builder.setUInt16Field(16)
    try builder.setUInt32Field(32)
    try builder.setUInt64Field(UInt64.max)
    try builder.setFloat32Field(1.25)
    try builder.setFloat64Field(-2.5)
    try builder.setTextField("typed")
    try builder.setDataField([0, 1, 255])
    let nested = try builder.initStructField()
    try nested.setTextField("nested")
    try builder.setEnumField(TestEnum(rawValue: 65_000))
    try builder.setVoidList([(), ()])
    try builder.setBoolList([true, false, true])
    try builder.setInt8List([-1, 2])
    try builder.setInt16List([-3, 4])
    try builder.setInt32List([1, -2, 3])
    try builder.setInt64List([-5, 6])
    try builder.setUInt8List([7, 8])
    try builder.setUInt16List([9, 10])
    try builder.setUInt32List([11, 12])
    try builder.setUInt64List([13, 14])
    try builder.setFloat32List([1.5, -2.5])
    try builder.setFloat64List([3.5, -4.5])
    try builder.setTextList(["one", "two"])
    try builder.setDataList([[1, 2], [3]])
    try builder.setEnumList([.foo, TestEnum(rawValue: 999)])

    let elementMessage = try MessageBuilder()
    let elementBuilder = try TestAllTypes.initRoot(in: elementMessage)
    try elementBuilder.setTextField("element")
    let elementReader = TestAllTypes.Reader(try elementMessage.asReader().rootStruct())
    try builder.setStructList([elementReader])

    let reader = TestAllTypes.Reader(try message.asReader().rootStruct())
    #expect(try reader.boolField)
    #expect(try reader.int8Field == -8)
    #expect(try reader.int16Field == -16)
    #expect(try reader.int32Field == -123_456)
    #expect(try reader.int64Field == -64)
    #expect(try reader.uInt8Field == 8)
    #expect(try reader.uInt16Field == 16)
    #expect(try reader.uInt32Field == 32)
    #expect(try reader.uInt64Field == UInt64.max)
    #expect(try reader.float32Field == 1.25)
    #expect(try reader.float64Field == -2.5)
    #expect(try reader.textField == "typed")
    #expect(try reader.dataField == [0, 1, 255])
    #expect(try reader.structField.textField == "nested")
    #expect(try reader.enumField.rawValue == 65_000)
    #expect(try reader.voidList.count == 2)
    #expect(try reader.boolList == [true, false, true])
    #expect(try reader.int8List == [-1, 2])
    #expect(try reader.int16List == [-3, 4])
    #expect(try reader.int32List == [1, -2, 3])
    #expect(try reader.int64List == [-5, 6])
    #expect(try reader.uInt8List == [7, 8])
    #expect(try reader.uInt16List == [9, 10])
    #expect(try reader.uInt32List == [11, 12])
    #expect(try reader.uInt64List == [13, 14])
    #expect(try reader.float32List == [1.5, -2.5])
    #expect(try reader.float64List == [3.5, -4.5])
    #expect(try reader.textList == ["one", "two"])
    #expect(try reader.dataList == [[1, 2], [3]])
    #expect(try reader.structList.first?.textField == "element")
    #expect(try reader.enumList.map(\.rawValue) == [0, 999])
    #expect(try reader.hasTextField)
    #expect(try reader.hasDataField)
    #expect(try reader.hasStructField)
    #expect(try reader.hasBoolList)
    #expect(constTestValue == "A const text test value.")

    let defaultsMessage = try MessageBuilder()
    _ = try TestDefaults.initRoot(in: defaultsMessage)
    let defaults = TestDefaults.Reader(try defaultsMessage.asReader().rootStruct())
    #expect(try defaults.boolField)
    #expect(try defaults.int8Field == -123)
    #expect(try defaults.int16Field == -12_345)
    #expect(try defaults.int32Field == -12_345_678)
    #expect(try defaults.int64Field == -123_456_789_012_345)
    #expect(try defaults.uInt8Field == 234)
    #expect(try defaults.uInt16Field == 45_678)
    #expect(try defaults.uInt32Field == 3_456_789_012)
    #expect(try defaults.uInt64Field == 12_345_678_901_234_567_890)
    #expect(try defaults.float32Field == 1_234.5)
    #expect(try defaults.float64Field == -1.23e47)
    #expect(try defaults.textField == "foo")
    #expect(try defaults.dataField == Array("bar".utf8))
    #expect(try defaults.structField.textField == "baz")
    #expect(try defaults.structField.dataField == Array("qux".utf8))
    #expect(try defaults.structField.structField.textField == "nested")
    #expect(try defaults.structField.structField.structField.textField == "really nested")
    #expect(try defaults.voidList.count == 6)
    #expect(try defaults.boolList == [true, false, false, true])
    #expect(try defaults.int8List == [111, -111])
    #expect(try defaults.int16List == [11_111, -11_111])
    #expect(try defaults.int32List == [111_111_111, -111_111_111])
    #expect(try defaults.int64List == [1_111_111_111_111_111_111, -1_111_111_111_111_111_111])
    #expect(try defaults.uInt8List == [111, 222])
    #expect(try defaults.uInt16List == [33_333, 44_444])
    #expect(try defaults.uInt32List == [3_333_333_333])
    #expect(try defaults.uInt64List == [11_111_111_111_111_111_111])
    let defaultFloat32 = try defaults.float32List
    #expect(defaultFloat32.prefix(3) == [5_555.5, .infinity, -.infinity])
    #expect(defaultFloat32.last?.isNaN == true)
    let defaultFloat64 = try defaults.float64List
    #expect(defaultFloat64.prefix(3) == [7_777.75, .infinity, -.infinity])
    #expect(defaultFloat64.last?.isNaN == true)
    #expect(try defaults.textList == ["plugh", "xyzzy", "thud"])
    #expect(
        try defaults.dataList == [
            Array("oops".utf8), Array("exhausted".utf8), Array("rfc3092".utf8),
        ])
    #expect(
        try defaults.structList.map { try $0.textField } == [
            "structlist 1", "structlist 2", "structlist 3",
        ])
    #expect(try defaults.enumField == .corge)
    #expect(try defaults.enumList == [.foo, .garply])
    #expect(try !defaults.hasTextField)
    #expect(try !defaults.hasDataField)
    #expect(try !defaults.hasStructField)
    #expect(try !defaults.hasBoolList)
}
