import CapnProto
import CapnProtoSchema
import Testing

// Ported behavior from capnproto@3a82de9b schema-loader-test.c++: incremental
// dependencies, upgrade/downgrade replacement, and invalid field offsets.
@Test func schemaLoaderValidatesAndReplacesNodes() throws {
    let field = SchemaField(
        name: "value", codeOrder: 0,
        storage: .slot(offset: 0, type: .uint64, defaultValue: .uint64(0)))
    let old = SchemaNode(
        id: 1, displayName: "Record",
        kind: .structure(
            dataWordCount: 1, pointerCount: 0, preferredListEncoding: .inlineComposite,
            isGroup: false, discriminantCount: 0, discriminantOffset: 0, fields: [field]))
    let extra = SchemaField(
        name: "extra", codeOrder: 1,
        storage: .slot(offset: 1, type: .uint64, defaultValue: .uint64(0)))
    let new = SchemaNode(
        id: 1, displayName: "Record",
        kind: .structure(
            dataWordCount: 2, pointerCount: 0, preferredListEncoding: .inlineComposite,
            isGroup: false, discriminantCount: 0, discriminantOffset: 0,
            fields: [field, extra]))

    var loader = SchemaLoader()
    try loader.load(old)
    try loader.load(new)
    try loader.load(old)
    #expect(loader.registry.schema(id: 1)?.field(named: "extra") != nil)
    #expect(SchemaLoader.compatibility(of: new, with: old).canReadExisting)

    let changedDefault = SchemaNode(
        id: 1, displayName: "Record",
        kind: .structure(
            dataWordCount: 1, pointerCount: 0, preferredListEncoding: .inlineComposite,
            isGroup: false, discriminantCount: 0, discriminantOffset: 0,
            fields: [
                SchemaField(
                    name: "value", codeOrder: 0,
                    storage: .slot(offset: 0, type: .uint64, defaultValue: .uint64(1)))
            ]))
    let changedCompatibility = SchemaLoader.compatibility(of: changedDefault, with: old)
    #expect(!changedCompatibility.canReadExisting)
    #expect(!changedCompatibility.canWriteExisting)

    let invalid = SchemaNode(
        id: 2, displayName: "Invalid",
        kind: .structure(
            dataWordCount: 1, pointerCount: 0, preferredListEncoding: .inlineComposite,
            isGroup: false, discriminantCount: 0, discriminantOffset: 0,
            fields: [
                SchemaField(
                    name: "bad", codeOrder: 0,
                    storage: .slot(
                        offset: UInt32.max, type: .uint64, defaultValue: .uint64(0)))
            ]))
    #expect(throws: SchemaError.self) { try loader.load(invalid) }
}

// Deterministic coverage of each change class generated by
// compiler/evolution-test.c++ at the pinned upstream revision.
@Test func schemaLoaderMatchesPinnedEvolutionChangeClasses() throws {
    func slot(
        _ name: String, _ codeOrder: UInt16, _ offset: UInt32, _ type: SchemaType = .int32,
        _ defaultValue: SchemaDefaultValue = .int32(0)
    ) -> SchemaField {
        SchemaField(
            name: name, codeOrder: codeOrder,
            storage: .slot(offset: offset, type: type, defaultValue: defaultValue))
    }
    func structure(_ fields: [SchemaField], words: UInt16 = 1) -> SchemaNode {
        SchemaNode(
            id: 100, displayName: "EvolvingStruct",
            kind: .structure(
                dataWordCount: words, pointerCount: 0,
                preferredListEncoding: .inlineComposite, isGroup: false,
                discriminantCount: 0, discriminantOffset: 0, fields: fields))
    }

    let original = structure([slot("foo", 0, 0), slot("bar", 1, 1)])
    let added = structure(
        [slot("foo", 0, 0), slot("bar", 1, 1), slot("baz", 2, 2)], words: 2)
    #expect(SchemaLoader.compatibility(of: added, with: original).canReadExisting)

    let renamed = structure([slot("fooXx", 0, 0), slot("bar", 1, 1)])
    #expect(SchemaLoader.compatibility(of: renamed, with: original).isEquivalent)
    let reordered = structure([slot("foo", 1, 0), slot("bar", 0, 1)])
    #expect(SchemaLoader.compatibility(of: reordered, with: original).isEquivalent)

    let nullList = try MessageReader(segments: [[UInt8](repeating: 0, count: 8)]).rootList()
    let primitiveList = structure([slot("values", 0, 0, .list(.int32), .list(nullList))])
    let structList = structure([
        slot("values", 0, 0, .list(.structure(id: 200, brand: SchemaBrand())), .list(nullList))
    ])
    #expect(SchemaLoader.compatibility(of: structList, with: primitiveList).isEquivalent)
    let boolList = structure([slot("values", 0, 0, .list(.bool), .list(nullList))])
    #expect(!SchemaLoader.compatibility(of: structList, with: boolList).canReadExisting)

    let changedType = structure([slot("foo", 0, 0, .text, .text("")), slot("bar", 1, 1)])
    #expect(!SchemaLoader.compatibility(of: changedType, with: original).canReadExisting)
    let changedDefault = structure([
        slot("foo", 0, 0, .int32, .int32(1)), slot("bar", 1, 1),
    ])
    #expect(!SchemaLoader.compatibility(of: changedDefault, with: original).canReadExisting)

    let group = SchemaNode(
        id: 200, displayName: "EvolvingStruct.group", scopeID: 100,
        kind: .structure(
            dataWordCount: 1, pointerCount: 0, preferredListEncoding: .inlineComposite,
            isGroup: true, discriminantCount: 0, discriminantOffset: 0,
            fields: [slot("foo", 0, 0)]))
    let wrapped = structure([
        SchemaField(name: "group", codeOrder: 0, storage: .group(typeID: 200)),
        slot("bar", 1, 1),
    ])
    var loader = SchemaLoader()
    try loader.load(original)
    try loader.load(group)
    try loader.load(wrapped)
}
