import CapnProto
import CapnProtoSchema

public enum CapnProtoCompilerRuntime {
    public static let isImplemented = false
}

public struct GeneratedSwiftFile: Equatable, Sendable {
    public let path: String
    public let contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

public enum SwiftGeneratorError: Error, Equatable, CustomStringConvertible {
    case duplicateNodeID(Schema.ID)
    case missingNode(Schema.ID)
    case requestedNodeIsNotFile(Schema.ID)
    case invalidOutputPath(String)

    public var description: String {
        switch self {
        case .duplicateNodeID(let id): return "duplicate schema node ID \(hex(id))"
        case .missingNode(let id): return "missing schema node \(hex(id))"
        case .requestedNodeIsNotFile(let id):
            return "requested node \(hex(id)) is not a file"
        case .invalidOutputPath(let path): return "invalid generated output path: \(path)"
        }
    }
}

public struct SwiftGenerator {
    public init() {}

    public func generate(_ request: Schema.CodeGeneratorRequest) throws -> [GeneratedSwiftFile] {
        let nodes = try request.nodes
        var byID = [Schema.ID: Schema.Node]()
        for node in nodes {
            let id = try node.id
            guard byID.updateValue(node, forKey: id) == nil else {
                throw SwiftGeneratorError.duplicateNodeID(id)
            }
        }

        return try request.requestedFiles.map { requested in
            let id = try requested.id
            guard let file = byID[id] else { throw SwiftGeneratorError.missingNode(id) }
            guard try file.kind == .file else {
                throw SwiftGeneratorError.requestedNodeIsNotFile(id)
            }
            for imported in try requested.imports where byID[try imported.id] == nil {
                throw SwiftGeneratorError.missingNode(try imported.id)
            }

            let filename = try requested.filename
            let path = try outputPath(for: filename)
            let body = try emitFile(file, nodes: byID, sourceName: filename)
            return GeneratedSwiftFile(path: path, contents: body)
        }
    }

    private func emitFile(
        _ file: Schema.Node, nodes: [Schema.ID: Schema.Node], sourceName: String
    ) throws -> String {
        var lines = [
            "// Generated by capnpc-swift. DO NOT EDIT.",
            "// source: \(sourceName)",
            "",
            "import CapnProto",
            "",
        ]
        for nested in try file.nestedNodes {
            try emitDeclaration(nested, nodes: nodes, indent: "", into: &lines)
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func emitDeclaration(
        _ nested: Schema.NestedNode, nodes: [Schema.ID: Schema.Node], indent: String,
        into lines: inout [String]
    ) throws {
        let id = try nested.id
        guard let node = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
        let name = swiftIdentifier(try nested.name)
        lines.append("\(indent)public enum \(name) {")
        for child in try node.nestedNodes {
            try emitDeclaration(child, nodes: nodes, indent: indent + "    ", into: &lines)
        }
        lines.append("\(indent)}")
        lines.append("")
    }
}

public func swiftIdentifier(_ source: String) -> String {
    swiftKeywords.contains(source) ? "`\(source)`" : source
}

private func outputPath(for source: String) throws -> String {
    guard !source.isEmpty, !source.hasPrefix("/"), !source.split(separator: "/").contains("..")
    else {
        throw SwiftGeneratorError.invalidOutputPath(source)
    }
    return source + ".swift"
}

private func hex(_ value: UInt64) -> String {
    "0x" + String(value, radix: 16)
}

private let swiftKeywords: Set<String> = [
    "Any", "Protocol", "Self", "Type", "actor", "as", "associatedtype", "associativity",
    "async", "await", "borrowing", "break", "case", "catch", "class", "consume",
    "consuming", "continue", "convenience", "copy", "default", "defer", "deinit", "didSet",
    "distributed", "do", "dynamic", "else", "enum", "extension", "fallthrough", "false",
    "fileprivate", "final", "for", "func", "get", "guard", "if", "import", "indirect",
    "infix", "init", "inout", "internal", "is", "isolated", "lazy", "left", "let",
    "macro", "mutating", "nil", "nonisolated", "nonmutating", "open", "operator",
    "optional", "override", "package", "postfix", "precedence", "precedencegroup", "prefix",
    "private", "protocol", "public", "repeat", "required", "rethrows", "return", "right",
    "safe", "self", "set", "some", "static", "struct", "subscript", "super", "switch",
    "throws", "true", "try", "typealias", "unowned", "unsafe", "var", "weak", "where",
    "while", "willSet",
]
