import CapnProto
import CapnProtoSchema

public enum CapnProtoCompilerRuntime {
    public static let isImplemented = false
}

public struct GeneratedSwiftFile: Equatable, Sendable {
    public let path: String
    public let contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

public enum SwiftGeneratorError: Error, Equatable, CustomStringConvertible {
    case duplicateNodeID(Schema.ID)
    case missingNode(Schema.ID)
    case requestedNodeIsNotFile(Schema.ID)
    case invalidOutputPath(String)
    case unsupportedSchema(String)

    public var description: String {
        switch self {
        case .duplicateNodeID(let id): return "duplicate schema node ID \(hex(id))"
        case .missingNode(let id): return "missing schema node \(hex(id))"
        case .requestedNodeIsNotFile(let id):
            return "requested node \(hex(id)) is not a file"
        case .invalidOutputPath(let path): return "invalid generated output path: \(path)"
        case .unsupportedSchema(let detail): return "unsupported schema construct: \(detail)"
        }
    }
}

public struct SwiftGenerator {
    public init() {}

    public func generate(_ request: Schema.CodeGeneratorRequest) throws -> [GeneratedSwiftFile] {
        let nodes = try request.nodes
        var byID = [Schema.ID: Schema.Node]()
        for node in nodes {
            let id = try node.id
            guard byID.updateValue(node, forKey: id) == nil else {
                throw SwiftGeneratorError.duplicateNodeID(id)
            }
        }

        let names = try buildNames(nodes: byID)
        return try request.requestedFiles.map { requested in
            let id = try requested.id
            guard let file = byID[id] else { throw SwiftGeneratorError.missingNode(id) }
            guard try file.kind == .file else {
                throw SwiftGeneratorError.requestedNodeIsNotFile(id)
            }
            for imported in try requested.imports where byID[try imported.id] == nil {
                throw SwiftGeneratorError.missingNode(try imported.id)
            }

            let filename = try requested.filename
            let path = try outputPath(for: filename)
            let body = try emitFile(file, nodes: byID, names: names, sourceName: filename)
            return GeneratedSwiftFile(path: path, contents: body)
        }
    }

    private func emitFile(
        _ file: Schema.Node, nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String],
        sourceName: String
    ) throws -> String {
        var lines = [
            "// Generated by capnpc-swift. DO NOT EDIT.",
            "// source: \(sourceName)",
            "",
            "import CapnProto",
            "",
            "private func _capnpRequiredText(_ value: TextReader) throws -> String {",
            "    guard let string = value.string else { throw CapnProtoError.invalidText }",
            "    return string",
            "}",
            "",
        ]
        for nested in try file.nestedNodes {
            try emitDeclaration(nested, nodes: nodes, names: names, indent: "", into: &lines)
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func emitDeclaration(
        _ nested: Schema.NestedNode, nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String],
        indent: String, into lines: inout [String]
    ) throws {
        let id = try nested.id
        guard let node = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
        switch try node.kind {
        case .struct:
            try emitStruct(
                node, name: swiftIdentifier(try nested.name), nodes: nodes, names: names,
                indent: indent, into: &lines)
        case .enum:
            try emitEnum(node, name: swiftIdentifier(try nested.name), indent: indent, into: &lines)
        case .constant:
            try emitConstant(
                node, name: swiftIdentifier(try nested.name), names: names,
                indent: indent, into: &lines)
        case .interface:
            try emitInterfacePlaceholder(
                node, name: swiftIdentifier(try nested.name), nodes: nodes, names: names,
                indent: indent, into: &lines)
        default:
            try emitNamespace(
                node, name: swiftIdentifier(try nested.name), nodes: nodes,
                names: names, indent: indent, into: &lines)
        }
    }

    private func emitNamespace(
        _ node: Schema.Node, name: String, nodes: [Schema.ID: Schema.Node],
        names: [Schema.ID: String], indent: String, into lines: inout [String]
    ) throws {
        lines.append("\(indent)public enum \(name) {")
        for child in try node.nestedNodes {
            try emitDeclaration(
                child, nodes: nodes, names: names, indent: indent + "    ", into: &lines)
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitInterfacePlaceholder(
        _ node: Schema.Node, name: String, nodes: [Schema.ID: Schema.Node],
        names: [Schema.ID: String], indent: String, into lines: inout [String]
    ) throws {
        lines.append("\(indent)public enum \(name) {")
        lines.append("\(indent)    public struct Client {")
        lines.append("\(indent)        public let raw: AnyPointerReader")
        lines.append("\(indent)        public init(_ raw: AnyPointerReader) { self.raw = raw }")
        lines.append("\(indent)    }")
        for child in try node.nestedNodes {
            try emitDeclaration(
                child, nodes: nodes, names: names, indent: indent + "    ", into: &lines)
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitEnum(
        _ node: Schema.Node, name: String, indent: String, into lines: inout [String]
    ) throws {
        lines.append(
            "\(indent)public struct \(name): RawRepresentable, Equatable, Hashable, Sendable {")
        lines.append("\(indent)    public let rawValue: UInt16")
        lines.append("\(indent)    public init(rawValue: UInt16) { self.rawValue = rawValue }")
        for (rawValue, enumerant) in try node.enumerants.enumerated() {
            lines.append(
                "\(indent)    public static let \(swiftIdentifier(try enumerant.name)) = \(name)(rawValue: \(rawValue))"
            )
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitStruct(
        _ node: Schema.Node, name: String, nodes: [Schema.ID: Schema.Node],
        names: [Schema.ID: String], indent: String, into lines: inout [String]
    ) throws {
        lines.append("\(indent)public enum \(name) {")
        lines.append("\(indent)    public static let schemaID: UInt64 = \(try node.id)")
        lines.append("")
        lines.append("\(indent)    public struct Reader {")
        lines.append("\(indent)        public let raw: StructReader")
        lines.append("\(indent)        public init(_ raw: StructReader) { self.raw = raw }")
        for field in try node.fields where try field.kind == .slot {
            try emitReaderField(field, names: names, indent: indent + "        ", into: &lines)
        }
        lines.append("\(indent)    }")
        lines.append("")
        lines.append("\(indent)    public struct Builder {")
        lines.append("\(indent)        public let raw: StructBuilder")
        lines.append("\(indent)        public init(_ raw: StructBuilder) { self.raw = raw }")
        for field in try node.fields where try field.kind == .slot {
            try emitBuilderField(
                field, nodes: nodes, names: names, indent: indent + "        ", into: &lines)
        }
        lines.append("\(indent)    }")
        lines.append("")
        lines.append(
            "\(indent)    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions()) throws -> Reader {"
        )
        lines.append("\(indent)        let frame = try MessageFraming.decodePrefix(bytes)")
        lines.append(
            "\(indent)        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }"
        )
        lines.append(
            "\(indent)        return Reader(try frame.reader(options: options).rootStruct())")
        lines.append("\(indent)    }")
        lines.append("")
        lines.append(
            "\(indent)    public static func initRoot(in message: MessageBuilder) throws -> Builder {"
        )
        lines.append(
            "\(indent)        Builder(try message.initRootStruct(dataWords: \(try node.dataWordCount), pointerCount: \(try node.pointerCount)))"
        )
        lines.append("\(indent)    }")
        for child in try node.nestedNodes {
            lines.append("")
            try emitDeclaration(
                child, nodes: nodes, names: names, indent: indent + "    ", into: &lines)
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitReaderField(
        _ field: Schema.Field, names: [Schema.ID: String], indent: String,
        into lines: inout [String]
    ) throws {
        let name = swiftIdentifier(try field.name)
        let type = try field.type
        let swift = try swiftType(type, names: names)
        let offset = try field.offset
        lines.append("\(indent)public var \(name): \(swift) {")
        lines.append("\(indent)    get throws {")
        lines.append(
            "\(indent)        \(try readExpression(type, field: field, offset: offset, names: names))"
        )
        lines.append("\(indent)    }")
        lines.append("\(indent)}")
        if isPointer(try type.kind) {
            lines.append(
                "\(indent)public var has\(upperFirst(try field.name)): Bool { get throws { try raw.hasPointer(at: \(offset)) } }"
            )
        }
    }

    private func emitBuilderField(
        _ field: Schema.Field, nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String],
        indent: String,
        into lines: inout [String]
    ) throws {
        let originalName = try field.name
        let method = "set" + upperFirst(originalName)
        let type = try field.type
        let swift = try swiftType(type, names: names)
        let offset = try field.offset
        switch try type.kind {
        case .void:
            break
        case .bool:
            lines.append(
                "\(indent)public func \(method)(_ value: Bool) throws { try raw.setBool(atBit: \(offset), to: value, default: \(try defaultLiteral(field, names: names))) }"
            )
        case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
            lines.append(
                "\(indent)public func \(method)(_ value: \(swift)) throws { try raw.setInteger(atByte: \(try byteOffset(type, offset)), to: value, default: \(try defaultLiteral(field, names: names))) }"
            )
        case .float32:
            lines.append(
                "\(indent)public func \(method)(_ value: Float) throws { try raw.setFloat32(atByte: \(offset * 4), to: value, default: \(try defaultLiteral(field, names: names))) }"
            )
        case .float64:
            lines.append(
                "\(indent)public func \(method)(_ value: Double) throws { try raw.setFloat64(atByte: \(offset * 8), to: value, default: \(try defaultLiteral(field, names: names))) }"
            )
        case .enum:
            lines.append(
                "\(indent)public func \(method)(_ value: \(swift)) throws { try raw.setInteger(atByte: \(offset * 2), to: value.rawValue, default: \(try defaultLiteral(field, names: names)).rawValue) }"
            )
        case .text:
            lines.append(
                "\(indent)public func \(method)(_ value: String) throws { _ = try raw.setTextField(at: \(offset), to: value) }"
            )
        case .data:
            lines.append(
                "\(indent)public func \(method)(_ value: [UInt8]) throws { _ = try raw.setDataField(at: \(offset), to: value) }"
            )
        case .struct:
            let base = try schemaName(type, names: names)
            lines.append(
                "\(indent)public func \(method)(_ value: \(swift)) throws { try raw.setStructField(at: \(offset), copying: value.raw) }"
            )
            lines.append(
                "\(indent)public func init\(upperFirst(originalName))() throws -> \(base).Builder { \(base).Builder(try raw.initStructField(at: \(offset), dataWords: \(try structSize(type, nodes: nodes).0), pointerCount: \(try structSize(type, nodes: nodes).1))) }"
            )
        case .list:
            let element = try type.elementType
            if try element.kind == .struct {
                let size = try structSize(element, nodes: nodes)
                lines.append(
                    "\(indent)public func init\(upperFirst(originalName))(count: Int) throws -> StructListBuilder { try raw.initStructListField(at: \(offset), count: count, dataWords: \(size.0), pointerCount: \(size.1)) }"
                )
            } else {
                lines.append(
                    "\(indent)public func init\(upperFirst(originalName))(count: Int) throws -> ListBuilder { try raw.initListField(at: \(offset), elementSize: \(try listElementSize(element)), count: count) }"
                )
            }
            try emitListSetter(
                method: method, element: element, offset: offset, nodes: nodes, names: names,
                indent: indent, into: &lines)
        default:
            break
        }
    }

    private func emitListSetter(
        method: String, element: Schema.`Type`, offset: UInt32,
        nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String], indent: String,
        into lines: inout [String]
    ) throws {
        switch try element.kind {
        case .list, .interface, .anyPointer, .unknown:
            return
        default:
            break
        }
        let valueType = try swiftType(element, names: names)
        lines.append("\(indent)public func \(method)(_ values: [\(valueType)]) throws {")
        switch try element.kind {
        case .struct:
            let size = try structSize(element, nodes: nodes)
            lines.append(
                "\(indent)    let list = try raw.initStructListField(at: \(offset), count: values.count, dataWords: \(size.0), pointerCount: \(size.1))"
            )
            lines.append(
                "\(indent)    for (index, value) in values.enumerated() { try list[index].copyContent(from: value.raw) }"
            )
        default:
            let binding = try element.kind == .void ? "_" : "let list"
            lines.append(
                "\(indent)    \(binding) = try raw.initListField(at: \(offset), elementSize: \(try listElementSize(element)), count: values.count)"
            )
            switch try element.kind {
            case .void: break
            case .bool:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setBool(at: index, to: value) }"
                )
            case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setInteger(at: index, to: value) }"
                )
            case .float32:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setFloat32(at: index, to: value) }"
                )
            case .float64:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setFloat64(at: index, to: value) }"
                )
            case .enum:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setInteger(at: index, to: value.rawValue) }"
                )
            case .text:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setText(at: index, to: value) }"
                )
            case .data:
                lines.append(
                    "\(indent)    for (index, value) in values.enumerated() { try list.setData(at: index, to: value) }"
                )
            default: break
            }
        }
        lines.append("\(indent)}")
    }

    private func emitConstant(
        _ node: Schema.Node, name: String, names: [Schema.ID: String], indent: String,
        into lines: inout [String]
    ) throws {
        let type = try node.constantType
        let value = try node.constantValue
        let staticPrefix = indent.isEmpty ? "" : "static "
        switch try type.kind {
        case .struct:
            let bytes = try pointerValueBytes(value, type: type)
            lines.append(
                "\(indent)public \(staticPrefix)var \(name): \(try swiftType(type, names: names)) {"
            )
            lines.append("\(indent)    get throws {")
            lines.append(
                "\(indent)        let frame = try MessageFraming.decodePrefix(\(byteArray(bytes)))"
            )
            lines.append(
                "\(indent)        return \(try swiftType(type, names: names))(try frame.reader().rootStruct())"
            )
            lines.append("\(indent)    }")
            lines.append("\(indent)}")
        case .list:
            let bytes = try pointerValueBytes(value, type: type)
            lines.append(
                "\(indent)public \(staticPrefix)var \(name): \(try swiftType(type, names: names)) {"
            )
            lines.append("\(indent)    get throws {")
            lines.append(
                "\(indent)        let list = try MessageFraming.decodePrefix(\(byteArray(bytes))).reader().rootList()"
            )
            lines.append(
                "\(indent)        return \(try listRead(type.elementType, list: "list", names: names, depth: 0))"
            )
            lines.append("\(indent)    }")
            lines.append("\(indent)}")
        default:
            let storage = indent.isEmpty ? "let" : "static let"
            lines.append(
                "\(indent)public \(storage) \(name): \(try swiftType(type, names: names)) = \(try valueLiteral(value, type: type, names: names))"
            )
        }
        lines.append("")
    }
}

private func pointerValueBytes(_ value: Schema.Value, type: Schema.`Type`) throws -> [UInt8] {
    let message = try MessageBuilder(firstSegmentWords: 4096, allocationStrategy: .fixedSize)
    switch try type.kind {
    case .struct: _ = try message.setRoot(copying: value.structValue)
    case .list: try message.setRoot(copying: value.listValue)
    default: throw SwiftGeneratorError.unsupportedSchema("pointer constant \(try type.kind)")
    }
    return try message.framedBytes
}

private func byteArray(_ bytes: [UInt8]) -> String {
    "[" + bytes.map(String.init).joined(separator: ", ") + "]"
}

private func buildNames(nodes: [Schema.ID: Schema.Node]) throws -> [Schema.ID: String] {
    var result = [Schema.ID: String]()
    func visit(_ node: Schema.Node, prefix: String) throws {
        for nested in try node.nestedNodes {
            let id = try nested.id
            // Compiler requests may omit unused declarations from imported
            // files even though the imported file's nested-node table names them.
            guard let child = nodes[id] else { continue }
            let component = swiftIdentifier(try nested.name)
            let name = prefix.isEmpty ? component : prefix + "." + component
            result[id] = name
            try visit(child, prefix: name)
        }
    }
    for node in nodes.values where try node.kind == .file {
        try visit(node, prefix: "")
    }
    return result
}

private func swiftType(_ type: Schema.`Type`, names: [Schema.ID: String]) throws -> String {
    switch try type.kind {
    case .void: return "Void"
    case .bool: return "Bool"
    case .int8: return "Int8"
    case .int16: return "Int16"
    case .int32: return "Int32"
    case .int64: return "Int64"
    case .uint8: return "UInt8"
    case .uint16: return "UInt16"
    case .uint32: return "UInt32"
    case .uint64: return "UInt64"
    case .float32: return "Float"
    case .float64: return "Double"
    case .text: return "String"
    case .data: return "[UInt8]"
    case .list: return "[\(try swiftType(type.elementType, names: names))]"
    case .enum: return try schemaName(type, names: names)
    case .struct: return try schemaName(type, names: names) + ".Reader"
    case .interface: return try schemaName(type, names: names) + ".Client"
    case .anyPointer: return "AnyPointerReader"
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("type discriminant \(value)")
    }
}

private func readExpression(
    _ type: Schema.`Type`, field: Schema.Field, offset: UInt32, names: [Schema.ID: String]
) throws -> String {
    switch try type.kind {
    case .void: return "return ()"
    case .bool:
        return
            "return try raw.bool(atBit: \(offset), default: \(try defaultLiteral(field, names: names)))"
    case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
        return
            "return try raw.integer(atByte: \(try byteOffset(type, offset)), default: \(try defaultLiteral(field, names: names)))"
    case .float32:
        return
            "return try raw.float32(atByte: \(offset * 4), default: \(try defaultLiteral(field, names: names)))"
    case .float64:
        return
            "return try raw.float64(atByte: \(offset * 8), default: \(try defaultLiteral(field, names: names)))"
    case .text:
        let fallback = try defaultLiteral(field, names: names)
        return
            "return try raw.hasPointer(at: \(offset)) ? _capnpRequiredText(raw.textField(at: \(offset))) : \(fallback)"
    case .data:
        let fallback = try defaultLiteral(field, names: names)
        return
            "return try raw.hasPointer(at: \(offset)) ? raw.dataField(at: \(offset)).bytes : \(fallback)"
    case .enum:
        return
            "return \(try swiftType(type, names: names))(rawValue: try raw.integer(atByte: \(offset * 2), default: \(try field.defaultValue.enumValue)))"
    case .struct:
        let bytes = try pointerValueBytes(field.defaultValue, type: type)
        return
            "if try raw.hasPointer(at: \(offset)) { return \(try swiftType(type, names: names))(try raw.structField(at: \(offset))) }; let frame = try MessageFraming.decodePrefix(\(byteArray(bytes))); return \(try swiftType(type, names: names))(try frame.reader().rootStruct())"
    case .list:
        let bytes = try pointerValueBytes(field.defaultValue, type: type)
        return
            "let list = try raw.hasPointer(at: \(offset)) ? raw.listField(at: \(offset)) : MessageFraming.decodePrefix(\(byteArray(bytes))).reader().rootList(); return \(try listRead(type.elementType, list: "list", names: names, depth: 0))"
    case .anyPointer:
        return "return try raw.anyPointerField(at: \(offset))"
    case .interface:
        return "return \(try swiftType(type, names: names))(try raw.anyPointerField(at: \(offset)))"
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("type discriminant \(value)")
    }
}

private func listRead(
    _ type: Schema.`Type`, list: String, names: [Schema.ID: String], depth: Int
) throws -> String {
    let index = "index\(depth)"
    switch try type.kind {
    case .void: return "Array(repeating: (), count: \(list).count)"
    case .bool: return "try (0..<\(list).count).map { try \(list).bool(at: $0) }"
    case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
        return
            "try (0..<\(list).count).map { try \(list).integer(at: $0, as: \(try swiftType(type, names: names)).self) }"
    case .float32: return "try (0..<\(list).count).map { try \(list).float32(at: $0) }"
    case .float64: return "try (0..<\(list).count).map { try \(list).float64(at: $0) }"
    case .text:
        return
            "try (0..<\(list).count).map { try _capnpRequiredText(\(list).textPointerElement(at: $0)) }"
    case .data:
        return "try (0..<\(list).count).map { try \(list).dataPointerElement(at: $0).bytes }"
    case .enum:
        return
            "try (0..<\(list).count).map { \(try swiftType(type, names: names))(rawValue: try \(list).integer(at: $0, as: UInt16.self)) }"
    case .struct:
        return
            "try (0..<\(list).count).map { \(try swiftType(type, names: names))(try \(list).structElement(at: $0)) }"
    case .list:
        let child = "list\(depth + 1)"
        return
            "try (0..<\(list).count).map { \(index) in let \(child) = try \(list).pointerElement(at: \(index)); return \(try listRead(type.elementType, list: child, names: names, depth: depth + 1)) }"
    case .anyPointer:
        return "try (0..<\(list).count).map { try \(list).anyPointerElement(at: $0) }"
    case .interface:
        return
            "try (0..<\(list).count).map { \(try swiftType(type, names: names))(try \(list).anyPointerElement(at: $0)) }"
    default:
        throw SwiftGeneratorError.unsupportedSchema("list element \(try type.kind)")
    }
}

private func defaultLiteral(_ field: Schema.Field, names: [Schema.ID: String]) throws -> String {
    try valueLiteral(field.defaultValue, type: field.type, names: names)
}

private func valueLiteral(
    _ value: Schema.Value, type: Schema.`Type`, names: [Schema.ID: String]
) throws -> String {
    switch try type.kind {
    case .void: return "()"
    case .bool: return try value.boolValue ? "true" : "false"
    case .int8: return "Int8(\(try value.int8Value))"
    case .int16: return "Int16(\(try value.int16Value))"
    case .int32: return "Int32(\(try value.int32Value))"
    case .int64: return "Int64(\(try value.int64Value))"
    case .uint8: return "UInt8(\(try value.uint8Value))"
    case .uint16: return "UInt16(\(try value.uint16Value))"
    case .uint32: return "UInt32(\(try value.uint32Value))"
    case .uint64: return "UInt64(\(try value.uint64Value))"
    case .float32: return floatLiteral(Double(try value.float32Value), swiftType: "Float")
    case .float64: return floatLiteral(try value.float64Value, swiftType: "Double")
    case .text: return String(reflecting: try value.textValue)
    case .data: return "[" + (try value.dataValue).map(String.init).joined(separator: ", ") + "]"
    case .enum:
        return "\(try swiftType(type, names: names))(rawValue: \(try value.enumValue))"
    default:
        throw SwiftGeneratorError.unsupportedSchema("constant/default \(try type.kind)")
    }
}

private func floatLiteral(_ value: Double, swiftType: String) -> String {
    if value.isNaN { return "\(swiftType).nan" }
    if value == .infinity { return "\(swiftType).infinity" }
    if value == -.infinity { return "-\(swiftType).infinity" }
    return "\(swiftType)(\(value))"
}

private func byteOffset(_ type: Schema.`Type`, _ offset: UInt32) throws -> UInt32 {
    let width: UInt32
    switch try type.kind {
    case .int8, .uint8: width = 1
    case .int16, .uint16, .enum: width = 2
    case .int32, .uint32, .float32: width = 4
    case .int64, .uint64, .float64: width = 8
    default: throw SwiftGeneratorError.unsupportedSchema("data offset for \(try type.kind)")
    }
    return offset * width
}

private func listElementSize(_ type: Schema.`Type`) throws -> String {
    switch try type.kind {
    case .void: return ".void"
    case .bool: return ".bit"
    case .int8, .uint8: return ".byte"
    case .int16, .uint16, .enum: return ".twoBytes"
    case .int32, .uint32, .float32: return ".fourBytes"
    case .int64, .uint64, .float64: return ".eightBytes"
    case .text, .data, .list, .struct, .interface, .anyPointer: return ".pointer"
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("list element discriminant \(value)")
    }
}

private func structSize(
    _ type: Schema.`Type`, nodes: [Schema.ID: Schema.Node]
) throws -> (UInt16, UInt16) {
    let id = try type.typeID
    guard let node = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
    return try (node.dataWordCount, node.pointerCount)
}

private func schemaName(_ type: Schema.`Type`, names: [Schema.ID: String]) throws -> String {
    let id = try type.typeID
    guard let name = names[id] else { throw SwiftGeneratorError.missingNode(id) }
    return name
}

private func isPointer(_ kind: Schema.TypeKind) -> Bool {
    switch kind {
    case .text, .data, .list, .struct, .interface, .anyPointer: return true
    default: return false
    }
}

private func upperFirst(_ value: String) -> String {
    guard let first = value.first else { return value }
    return String(first).uppercased() + value.dropFirst()
}

public func swiftIdentifier(_ source: String) -> String {
    swiftKeywords.contains(source) ? "`\(source)`" : source
}

private func outputPath(for source: String) throws -> String {
    guard !source.isEmpty, !source.hasPrefix("/"), !source.split(separator: "/").contains("..")
    else {
        throw SwiftGeneratorError.invalidOutputPath(source)
    }
    return source + ".swift"
}

private func hex(_ value: UInt64) -> String {
    "0x" + String(value, radix: 16)
}

private let swiftKeywords: Set<String> = [
    "Any", "Protocol", "Self", "Type", "actor", "as", "associatedtype", "associativity",
    "async", "await", "borrowing", "break", "case", "catch", "class", "consume",
    "consuming", "continue", "convenience", "copy", "default", "defer", "deinit", "didSet",
    "distributed", "do", "dynamic", "else", "enum", "extension", "fallthrough", "false",
    "fileprivate", "final", "for", "func", "get", "guard", "if", "import", "indirect",
    "infix", "init", "inout", "internal", "is", "isolated", "lazy", "left", "let",
    "macro", "mutating", "nil", "nonisolated", "nonmutating", "open", "operator",
    "optional", "override", "package", "postfix", "precedence", "precedencegroup", "prefix",
    "private", "protocol", "public", "repeat", "required", "rethrows", "return", "right",
    "safe", "self", "set", "some", "static", "struct", "subscript", "super", "switch",
    "throws", "true", "try", "typealias", "unowned", "unsafe", "var", "weak", "where",
    "while", "willSet",
]
