import CapnProto
import CapnProtoSchema

public enum CapnProtoCompilerRuntime {
    public static let isImplemented = false
}

public struct GeneratedSwiftFile: Equatable, Sendable {
    public let path: String
    public let contents: String

    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

public enum SwiftGeneratorError: Error, Equatable, CustomStringConvertible {
    case duplicateNodeID(Schema.ID)
    case missingNode(Schema.ID)
    case requestedNodeIsNotFile(Schema.ID)
    case invalidOutputPath(String)
    case unsupportedSchema(String)
    case sourceLocated(source: String, startByte: UInt32, endByte: UInt32, detail: String)

    public var description: String {
        switch self {
        case .duplicateNodeID(let id): return "duplicate schema node ID \(hex(id))"
        case .missingNode(let id): return "missing schema node \(hex(id))"
        case .requestedNodeIsNotFile(let id):
            return "requested node \(hex(id)) is not a file"
        case .invalidOutputPath(let path): return "invalid generated output path: \(path)"
        case .unsupportedSchema(let detail): return "unsupported schema construct: \(detail)"
        case .sourceLocated(let source, let start, let end, let detail):
            return "\(source):bytes \(start)-\(end): \(detail)"
        }
    }
}

public struct SwiftGenerator {
    public init() {}

    public func generate(_ request: Schema.CodeGeneratorRequest) throws -> [GeneratedSwiftFile] {
        let nodes = try request.nodes
        var byID = [Schema.ID: Schema.Node]()
        for node in nodes {
            let id = try node.id
            guard byID.updateValue(node, forKey: id) == nil else {
                throw SwiftGeneratorError.duplicateNodeID(id)
            }
        }

        let names = try buildNames(nodes: byID)
        return try request.requestedFiles.map { requested in
            let id = try requested.id
            guard let file = byID[id] else { throw SwiftGeneratorError.missingNode(id) }
            guard try file.kind == .file else {
                throw SwiftGeneratorError.requestedNodeIsNotFile(id)
            }
            for imported in try requested.imports where byID[try imported.id] == nil {
                throw SwiftGeneratorError.missingNode(try imported.id)
            }

            let filename = try requested.filename
            let path = try outputPath(for: filename)
            let body = try emitFile(file, nodes: byID, names: names, sourceName: filename)
            return GeneratedSwiftFile(path: path, contents: body)
        }
    }

    private func emitFile(
        _ file: Schema.Node, nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String],
        sourceName: String
    ) throws -> String {
        var lines = [
            "// Generated by capnpc-swift. DO NOT EDIT.",
            "// source: \(sourceName)",
            "",
            "import CapnProto",
        ]
        if try fileNeedsRPC(file, nodes: nodes) {
            lines.append("import CapnProtoRPC")
        }
        lines.append(contentsOf: [
            "",
            "private func _capnpRequiredText(_ value: TextReader) throws -> String {",
            "    guard let string = value.string else { throw CapnProtoError.invalidText }",
            "    return string",
            "}",
            "",
        ])
        for nested in try file.nestedNodes {
            do {
                try emitDeclaration(nested, nodes: nodes, names: names, indent: "", into: &lines)
            } catch SwiftGeneratorError.unsupportedSchema(let detail) {
                guard let node = nodes[try nested.id] else {
                    throw SwiftGeneratorError.missingNode(try nested.id)
                }
                throw SwiftGeneratorError.sourceLocated(
                    source: sourceName, startByte: try node.startByte, endByte: try node.endByte,
                    detail: detail)
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func emitDeclaration(
        _ nested: Schema.NestedNode, nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String],
        indent: String, into lines: inout [String]
    ) throws {
        let id = try nested.id
        guard let node = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
        switch try node.kind {
        case .struct:
            try emitStruct(
                node, name: swiftIdentifier(try nested.name), nodes: nodes, names: names,
                indent: indent, into: &lines)
        case .enum:
            try emitEnum(node, name: swiftIdentifier(try nested.name), indent: indent, into: &lines)
        case .constant:
            try emitConstant(
                node, name: swiftIdentifier(try nested.name), names: names,
                indent: indent, into: &lines)
        case .interface:
            try emitInterface(
                node, name: swiftIdentifier(try nested.name), nodes: nodes, names: names,
                indent: indent, into: &lines)
        case .file, .annotation:
            try emitNamespace(
                node, name: swiftIdentifier(try nested.name), nodes: nodes,
                names: names, indent: indent, into: &lines)
        case .unknown(let value):
            throw SwiftGeneratorError.unsupportedSchema("node discriminant \(value)")
        }
    }

    private func emitNamespace(
        _ node: Schema.Node, name: String, nodes: [Schema.ID: Schema.Node],
        names: [Schema.ID: String], indent: String, into lines: inout [String]
    ) throws {
        lines.append("\(indent)public enum \(name) {")
        for child in try node.nestedNodes {
            try emitDeclaration(
                child, nodes: nodes, names: names, indent: indent + "    ", into: &lines)
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitInterface(
        _ node: Schema.Node, name: String, nodes: [Schema.ID: Schema.Node],
        names: [Schema.ID: String], indent: String, into lines: inout [String]
    ) throws {
        let interfaceID = try node.id
        let methods = try node.methods
        let superclasses = try node.superclasses
        lines.append("\(indent)public enum \(name) {")
        lines.append("\(indent)    public static let schemaID: UInt64 = \(interfaceID)")
        lines.append(
            "\(indent)    public static let superclassIDs: [UInt64] = [\(try superclasses.map { String(try $0.id) }.joined(separator: ", "))]"
        )
        lines.append("")
        lines.append("\(indent)    public struct Client {")
        lines.append("\(indent)        public let raw: CapabilityClient")
        lines.append("\(indent)        public init(_ raw: CapabilityClient) { self.raw = raw }")
        lines.append(
            "\(indent)        public init(_ pointer: AnyPointerReader) { raw = CapabilityClient(pointer: pointer) }"
        )
        for method in methods {
            let methodName = swiftIdentifier(try method.name)
            let params = try methodTypeName(method.paramStructType, names: names)
            let results = try methodTypeName(method.resultStructType, names: names)
            if try method.isStreaming {
                lines.append(
                    "\(indent)        public func \(methodName)(_ params: \(params).Reader) async throws { _ = try await raw.call(Methods.\(methodName), params: params.raw) }"
                )
            } else {
                let pipeline = swiftIdentifier(upperFirst(try method.name) + "Pipeline")
                let requestName = swiftIdentifier(try method.name + "Request")
                lines.append(
                    "\(indent)        public func \(requestName)(_ params: \(params).Reader) -> \(pipeline) { \(pipeline)(raw.startCall(Methods.\(methodName), params: params.raw)) }"
                )
                lines.append(
                    "\(indent)        public func \(methodName)(_ params: \(params).Reader) async throws -> \(results).Reader { try await \(requestName)(params).response() }"
                )
            }
        }
        for superclass in superclasses {
            guard let inheritedName = names[try superclass.id] else {
                throw SwiftGeneratorError.missingNode(try superclass.id)
            }
            let shortName =
                inheritedName.split(separator: ".").last.map(String.init) ?? inheritedName
            lines.append(
                "\(indent)        public var as\(upperFirst(shortName)): \(inheritedName).Client { \(inheritedName).Client(raw) }"
            )
        }
        lines.append("\(indent)    }")
        lines.append("")
        for method in methods where try !method.isStreaming {
            let pipeline = swiftIdentifier(upperFirst(try method.name) + "Pipeline")
            let results = try methodTypeName(method.resultStructType, names: names)
            guard let resultNode = nodes[try method.resultStructType] else {
                throw SwiftGeneratorError.missingNode(try method.resultStructType)
            }
            lines.append("\(indent)    public struct \(pipeline): Sendable {")
            lines.append("\(indent)        private let call: CapabilityCall")
            lines.append(
                "\(indent)        public init(_ call: CapabilityCall) { self.call = call }")
            lines.append(
                "\(indent)        public func response() async throws -> \(results).Reader { \(results).Reader(try await call.response()) }"
            )
            lines.append("\(indent)        public func cancel() { call.cancel() }")
            for field in try resultNode.fields where try field.kind == .slot {
                let type = try field.type
                guard try type.kind == .interface else { continue }
                let fieldName = swiftIdentifier(try field.name)
                let swift = try swiftType(type, names: names)
                lines.append("\(indent)        public var \(fieldName): \(swift) {")
                lines.append(
                    "\(indent)            \(swift)(call.pipelineCapability { raw in try \(results).Reader(raw).\(fieldName).raw })"
                )
                lines.append("\(indent)        }")
            }
            lines.append("\(indent)    }")
            lines.append("")
        }
        let inherited = try superclasses.map {
            guard let inheritedName = names[try $0.id] else {
                throw SwiftGeneratorError.missingNode(try $0.id)
            }
            return inheritedName + ".Server"
        }
        let inheritance = inherited.isEmpty ? "" : ": " + inherited.joined(separator: ", ")
        lines.append("\(indent)    public protocol Server\(inheritance) {")
        for method in methods {
            let methodName = swiftIdentifier(try method.name)
            let params = try methodTypeName(method.paramStructType, names: names)
            let results = try methodTypeName(method.resultStructType, names: names)
            if try method.isStreaming {
                lines.append(
                    "\(indent)        func \(methodName)(_ params: \(params).Reader) async throws")
            } else {
                lines.append(
                    "\(indent)        func \(methodName)(_ params: \(params).Reader, results: \(results).Builder) async throws"
                )
            }
        }
        lines.append("\(indent)    }")
        lines.append("")
        let allInterfaceIDs = [String(interfaceID)] + (try superclasses.map { String(try $0.id) })
        let allMethodTables =
            ["Methods.all"]
            + (try superclasses.map {
                guard let inheritedName = names[try $0.id] else {
                    throw SwiftGeneratorError.missingNode(try $0.id)
                }
                return inheritedName + ".Methods.all"
            })
        lines.append("\(indent)    public static func client(_ server: any Server) -> Client {")
        lines.append(
            "\(indent)        Client(CapabilityClient(target: LocalCapabilityTarget(interfaceIDs: Set([\(allInterfaceIDs.joined(separator: ", "))]), methods: \(allMethodTables.joined(separator: " + "))) { context in"
        )
        lines.append("\(indent)            try await dispatch(server, context: context)")
        lines.append("\(indent)        }))")
        lines.append("\(indent)    }")
        lines.append("")
        lines.append(
            "\(indent)    public static func dispatch(_ server: any Server, context: CapabilityRequestContext) async throws -> StructReader {"
        )
        lines.append(
            "\(indent)        switch (context.method.interfaceID, context.method.methodID) {")
        for (methodID, method) in methods.enumerated() {
            let methodName = swiftIdentifier(try method.name)
            let params = try methodTypeName(method.paramStructType, names: names)
            let results = try methodTypeName(method.resultStructType, names: names)
            guard let resultNode = nodes[try method.resultStructType] else {
                throw SwiftGeneratorError.missingNode(try method.resultStructType)
            }
            lines.append("\(indent)        case (schemaID, \(methodID)):")
            lines.append("\(indent)            try context.throwIfCancelled()")
            lines.append(
                "\(indent)            let response = try CapabilityResponseContext(dataWords: \(try resultNode.dataWordCount), pointerCount: \(try resultNode.pointerCount))"
            )
            if try method.isStreaming {
                lines.append(
                    "\(indent)            try await server.\(methodName)(\(params).Reader(context.params))"
                )
            } else {
                lines.append(
                    "\(indent)            let result = \(results).Builder(response.results)"
                )
                lines.append(
                    "\(indent)            try await server.\(methodName)(\(params).Reader(context.params), results: result)"
                )
            }
            lines.append("\(indent)            return try response.finish()")
        }
        for superclass in superclasses {
            guard let inheritedName = names[try superclass.id] else {
                throw SwiftGeneratorError.missingNode(try superclass.id)
            }
            lines.append("\(indent)        case (\(inheritedName).schemaID, _):")
            lines.append(
                "\(indent)            return try await \(inheritedName).dispatch(server, context: context)"
            )
        }
        lines.append("\(indent)        default:")
        lines.append(
            "\(indent)            throw CapabilityError.unknownMethod(interfaceID: context.method.interfaceID, methodID: context.method.methodID)"
        )
        lines.append("\(indent)        }")
        lines.append("\(indent)    }")
        lines.append("")
        lines.append("\(indent)    public enum Methods {")
        for (methodID, method) in methods.enumerated() {
            let methodName = swiftIdentifier(try method.name)
            lines.append(
                "\(indent)        public static let \(methodName) = CapabilityMethodDescriptor(interfaceID: \(interfaceID), methodID: \(methodID), name: \(String(reflecting: try method.name)), paramStructID: \(try method.paramStructType), resultStructID: \(try method.resultStructType), isStreaming: \(try method.isStreaming))"
            )
        }
        lines.append(
            "\(indent)        public static let all: [CapabilityMethodDescriptor] = [\(try methods.map { "\(swiftIdentifier(try $0.name))" }.joined(separator: ", "))]"
        )
        lines.append("\(indent)    }")
        for child in try node.nestedNodes {
            lines.append("")
            try emitDeclaration(
                child, nodes: nodes, names: names, indent: indent + "    ", into: &lines)
        }
        var emitted = Set(try node.nestedNodes.map { try $0.id })
        let qualifiedInterfaceName = names[interfaceID] ?? name
        for method in methods {
            for id in [try method.paramStructType, try method.resultStructType] {
                guard emitted.insert(id).inserted, let methodNode = nodes[id],
                    try methodNode.scopeID == 0, let qualified = names[id],
                    qualified.hasPrefix(qualifiedInterfaceName + ".")
                else { continue }
                let localName = String(qualified.dropFirst(qualifiedInterfaceName.count + 1))
                lines.append("")
                try emitStruct(
                    methodNode, name: localName, nodes: nodes, names: names,
                    indent: indent + "    ", into: &lines)
            }
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitEnum(
        _ node: Schema.Node, name: String, indent: String, into lines: inout [String]
    ) throws {
        lines.append(
            "\(indent)public struct \(name): RawRepresentable, Equatable, Hashable, Sendable {")
        lines.append("\(indent)    public let rawValue: UInt16")
        lines.append("\(indent)    public init(rawValue: UInt16) { self.rawValue = rawValue }")
        for (rawValue, enumerant) in try node.enumerants.enumerated() {
            lines.append(
                "\(indent)    public static let \(swiftIdentifier(try enumerant.name)) = \(name)(rawValue: \(rawValue))"
            )
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitStruct(
        _ node: Schema.Node, name: String, nodes: [Schema.ID: Schema.Node],
        names: [Schema.ID: String], indent: String, isGroup: Bool = false,
        into lines: inout [String]
    ) throws {
        lines.append("\(indent)public enum \(name) {")
        lines.append("\(indent)    public static let schemaID: UInt64 = \(try node.id)")
        if !isGroup {
            lines.append("\(indent)    public enum Pointer: CapnProtoPointerType {")
            lines.append(
                "\(indent)        public static func read(from pointer: AnyPointerReader) throws -> Reader { Reader(try pointer.asStruct()) }"
            )
            lines.append(
                "\(indent)        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws { try pointer.setStruct(value.raw) }"
            )
            lines.append("\(indent)    }")
        }
        let parameters = try node.parameters.map { try $0.name }
        if !parameters.isEmpty {
            lines.append(
                "\(indent)    public static let genericParameters: [String] = \(String(reflecting: parameters))"
            )
            let genericTypes = parameters.map { "\(swiftIdentifier($0)): CapnProtoPointerType" }
            lines.append(
                "\(indent)    public struct Generic<\(genericTypes.joined(separator: ", "))> {")
            lines.append("\(indent)        public struct Reader {")
            lines.append("\(indent)            public let raw: \(name).Reader")
            lines.append(
                "\(indent)            public init(_ raw: \(name).Reader) { self.raw = raw }")
            for field in try node.fields {
                guard let index = try parameterIndex(field, scopeID: node.id),
                    parameters.indices.contains(index)
                else { continue }
                let parameter = swiftIdentifier(parameters[index])
                let fieldName = swiftIdentifier(try field.name)
                lines.append("\(indent)            public var \(fieldName): \(parameter).Value {")
                lines.append(
                    "\(indent)                get throws { try \(parameter).read(from: raw.\(fieldName)) }"
                )
                lines.append("\(indent)            }")
            }
            lines.append("\(indent)        }")
            lines.append("\(indent)        public struct Builder {")
            lines.append("\(indent)            public let raw: \(name).Builder")
            lines.append(
                "\(indent)            public init(_ raw: \(name).Builder) { self.raw = raw }")
            for field in try node.fields {
                guard let index = try parameterIndex(field, scopeID: node.id),
                    parameters.indices.contains(index)
                else { continue }
                let parameter = swiftIdentifier(parameters[index])
                let fieldName = try field.name
                lines.append(
                    "\(indent)            public func set\(upperFirst(fieldName))(_ value: \(parameter).Value) throws {"
                )
                lines.append(
                    "\(indent)                let pointer = try raw.\(swiftIdentifier(fieldName))")
                lines.append("\(indent)                try \(parameter).write(value, to: pointer)")
                lines.append("\(indent)            }")
            }
            lines.append("\(indent)        }")
            lines.append(
                "\(indent)        public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions()) throws -> Reader {"
            )
            lines.append(
                "\(indent)            Reader(try \(name).readRoot(from: bytes, options: options))")
            lines.append("\(indent)        }")
            lines.append(
                "\(indent)        public static func initRoot(in message: MessageBuilder) throws -> Builder {"
            )
            lines.append("\(indent)            Builder(try \(name).initRoot(in: message))")
            lines.append("\(indent)        }")
            lines.append("\(indent)    }")
        }
        let unionFields = try node.fields.filter {
            try $0.discriminantValue != Schema.Field.noDiscriminant
        }
        if !unionFields.isEmpty {
            try emitUnionView(
                node, fields: unionFields, names: names, indent: indent + "    ", into: &lines)
        }
        lines.append("")
        lines.append("\(indent)    public struct Reader {")
        lines.append("\(indent)        public let raw: StructReader")
        lines.append("\(indent)        public init(_ raw: StructReader) { self.raw = raw }")
        for field in try node.fields {
            switch try field.kind {
            case .slot:
                try emitReaderField(field, names: names, indent: indent + "        ", into: &lines)
            case .group:
                let groupName = try groupName(field)
                lines.append(
                    "\(indent)        public var \(swiftIdentifier(try field.name)): \(groupName).Reader { \(groupName).Reader(raw) }"
                )
            case .unknown(let value):
                throw SwiftGeneratorError.unsupportedSchema("field discriminant \(value)")
            }
        }
        if !unionFields.isEmpty {
            lines.append("\(indent)        public var which: Which {")
            lines.append("\(indent)            get throws {")
            lines.append(
                "\(indent)                let tag = try raw.discriminant(atByte: \(try node.discriminantOffset * 2))"
            )
            lines.append("\(indent)                switch tag {")
            for field in unionFields {
                let caseName = swiftIdentifier(try field.name)
                let value = try field.discriminantValue
                if try field.kind == .slot, try field.type.kind == .void {
                    lines.append("\(indent)                case \(value): return .\(caseName)")
                } else if try field.kind == .group {
                    lines.append(
                        "\(indent)                case \(value): return .\(caseName)(\(caseName))"
                    )
                } else {
                    lines.append(
                        "\(indent)                case \(value): return .\(caseName)(try \(caseName))"
                    )
                }
            }
            lines.append("\(indent)                default: return .unknown(tag)")
            lines.append("\(indent)                }")
            lines.append("\(indent)            }")
            lines.append("\(indent)        }")
        }
        lines.append("\(indent)    }")
        lines.append("")
        lines.append("\(indent)    public struct Builder {")
        lines.append("\(indent)        public let raw: StructBuilder")
        lines.append("\(indent)        public init(_ raw: StructBuilder) { self.raw = raw }")
        let storage = try unionStorage(node, nodes: nodes)
        for field in try node.fields {
            let selection =
                try field.discriminantValue == Schema.Field.noDiscriminant
                ? nil
                : unionSelection(
                    field: field, node: node, storage: storage, indent: indent + "            ")
            switch try field.kind {
            case .slot:
                try emitBuilderField(
                    field, nodes: nodes, names: names, selection: selection,
                    indent: indent + "        ", into: &lines)
            case .group:
                let fieldName = try field.name
                let groupName = try groupName(field)
                if let selection {
                    lines.append(
                        "\(indent)        public func select\(upperFirst(fieldName))() throws -> \(groupName).Builder {"
                    )
                    lines.append(selection)
                    lines.append("\(indent)            return \(groupName).Builder(raw)")
                    lines.append("\(indent)        }")
                } else {
                    lines.append(
                        "\(indent)        public var \(swiftIdentifier(fieldName)): \(groupName).Builder { \(groupName).Builder(raw) }"
                    )
                }
            case .unknown(let value):
                throw SwiftGeneratorError.unsupportedSchema("field discriminant \(value)")
            }
        }
        if !unionFields.isEmpty {
            lines.append(
                "\(indent)        public func setUnknownDiscriminant(_ tag: UInt16) throws {"
            )
            lines.append(
                "\(indent)            try raw.setDiscriminant(atByte: \(try node.discriminantOffset * 2), to: tag)"
            )
            lines.append("\(indent)        }")
        }
        lines.append("\(indent)    }")
        lines.append("")
        if !isGroup {
            lines.append("")
            lines.append(
                "\(indent)    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions()) throws -> Reader {"
            )
            lines.append("\(indent)        let frame = try MessageFraming.decodePrefix(bytes)")
            lines.append(
                "\(indent)        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }"
            )
            lines.append(
                "\(indent)        return Reader(try frame.reader(options: options).rootStruct())")
            lines.append("\(indent)    }")
            lines.append("")
            lines.append(
                "\(indent)    public static func initRoot(in message: MessageBuilder) throws -> Builder {"
            )
            lines.append(
                "\(indent)        Builder(try message.initRootStruct(dataWords: \(try node.dataWordCount), pointerCount: \(try node.pointerCount)))"
            )
            lines.append("\(indent)    }")
        }
        for child in try node.nestedNodes {
            lines.append("")
            try emitDeclaration(
                child, nodes: nodes, names: names, indent: indent + "    ", into: &lines)
        }
        for field in try node.fields where try field.kind == .group {
            guard let group = nodes[try field.groupTypeID] else {
                throw SwiftGeneratorError.missingNode(try field.groupTypeID)
            }
            lines.append("")
            try emitStruct(
                group, name: try groupName(field), nodes: nodes, names: names,
                indent: indent + "    ", isGroup: true, into: &lines)
        }
        lines.append("\(indent)}")
        lines.append("")
    }

    private func emitReaderField(
        _ field: Schema.Field, names: [Schema.ID: String], indent: String,
        into lines: inout [String]
    ) throws {
        let name = swiftIdentifier(try field.name)
        let type = try field.type
        let swift = try swiftType(type, names: names)
        let offset = try field.offset
        lines.append("\(indent)public var \(name): \(swift) {")
        lines.append("\(indent)    get throws {")
        lines.append(
            "\(indent)        \(try readExpression(type, field: field, offset: offset, names: names))"
        )
        lines.append("\(indent)    }")
        lines.append("\(indent)}")
        if isPointer(try type.kind) {
            lines.append(
                "\(indent)public var has\(upperFirst(try field.name)): Bool { get throws { try raw.hasPointer(at: \(offset)) } }"
            )
        }
    }

    private func emitUnionView(
        _ node: Schema.Node, fields: [Schema.Field], names: [Schema.ID: String], indent: String,
        into lines: inout [String]
    ) throws {
        lines.append("\(indent)public enum Which {")
        for field in fields {
            let name = swiftIdentifier(try field.name)
            switch try field.kind {
            case .group:
                lines.append("\(indent)    case \(name)(\(try groupName(field)).Reader)")
            case .slot:
                if try field.type.kind == .void {
                    lines.append("\(indent)    case \(name)")
                } else {
                    lines.append(
                        "\(indent)    case \(name)(\(try swiftType(field.type, names: names)))"
                    )
                }
            case .unknown(let value):
                throw SwiftGeneratorError.unsupportedSchema("field discriminant \(value)")
            }
        }
        lines.append("\(indent)    case unknown(UInt16)")
        lines.append("\(indent)}")
    }

    private func emitBuilderField(
        _ field: Schema.Field, nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String],
        selection: String?, indent: String,
        into lines: inout [String]
    ) throws {
        let originalName = try field.name
        let method = "set" + upperFirst(originalName)
        let type = try field.type
        let swift = try swiftType(type, names: names)
        let offset = try field.offset
        switch try type.kind {
        case .void:
            if let selection {
                lines.append("\(indent)public func \(method)() throws {")
                lines.append(selection)
                lines.append("\(indent)}")
            }
        case .bool:
            try emitSetter(
                signature: "\(method)(_ value: Bool)", selection: selection, indent: indent,
                statement:
                    "try raw.setBool(atBit: \(offset), to: value, default: \(try defaultLiteral(field, names: names)))",
                into: &lines)
        case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
            try emitSetter(
                signature: "\(method)(_ value: \(swift))", selection: selection, indent: indent,
                statement:
                    "try raw.setInteger(atByte: \(try byteOffset(type, offset)), to: value, default: \(try defaultLiteral(field, names: names)))",
                into: &lines)
        case .float32:
            try emitSetter(
                signature: "\(method)(_ value: Float)", selection: selection, indent: indent,
                statement:
                    "try raw.setFloat32(atByte: \(offset * 4), to: value, default: \(try defaultLiteral(field, names: names)))",
                into: &lines)
        case .float64:
            try emitSetter(
                signature: "\(method)(_ value: Double)", selection: selection, indent: indent,
                statement:
                    "try raw.setFloat64(atByte: \(offset * 8), to: value, default: \(try defaultLiteral(field, names: names)))",
                into: &lines)
        case .enum:
            try emitSetter(
                signature: "\(method)(_ value: \(swift))", selection: selection, indent: indent,
                statement:
                    "try raw.setInteger(atByte: \(offset * 2), to: value.rawValue, default: \(try defaultLiteral(field, names: names)).rawValue)",
                into: &lines)
        case .text:
            try emitSetter(
                signature: "\(method)(_ value: String)", selection: selection, indent: indent,
                statement: "_ = try raw.setTextField(at: \(offset), to: value)", into: &lines)
        case .data:
            try emitSetter(
                signature: "\(method)(_ value: [UInt8])", selection: selection, indent: indent,
                statement: "_ = try raw.setDataField(at: \(offset), to: value)", into: &lines)
        case .struct:
            let base = try schemaName(type, names: names)
            try emitSetter(
                signature: "\(method)(_ value: \(swift))", selection: selection, indent: indent,
                statement: "try raw.setStructField(at: \(offset), copying: value.raw)", into: &lines
            )
            lines.append(
                "\(indent)public func init\(upperFirst(originalName))() throws -> \(base).Builder {"
            )
            if let selection { lines.append(selection) }
            lines.append(
                "\(indent)    return \(base).Builder(try raw.initStructField(at: \(offset), dataWords: \(try structSize(type, nodes: nodes).0), pointerCount: \(try structSize(type, nodes: nodes).1)))"
            )
            lines.append("\(indent)}")
        case .list:
            let element = try type.elementType
            if try element.kind == .struct {
                let size = try structSize(element, nodes: nodes)
                lines.append(
                    "\(indent)public func init\(upperFirst(originalName))(count: Int) throws -> StructListBuilder {"
                )
                if let selection { lines.append(selection) }
                lines.append(
                    "\(indent)    return try raw.initStructListField(at: \(offset), count: count, dataWords: \(size.0), pointerCount: \(size.1))"
                )
                lines.append("\(indent)}")
            } else {
                lines.append(
                    "\(indent)public func init\(upperFirst(originalName))(count: Int) throws -> ListBuilder {"
                )
                if let selection { lines.append(selection) }
                lines.append(
                    "\(indent)    return try raw.initListField(at: \(offset), elementSize: \(try listElementSize(element)), count: count)"
                )
                lines.append("\(indent)}")
            }
            try emitListSetter(
                method: method, element: element, offset: offset, nodes: nodes, names: names,
                selection: selection, indent: indent, into: &lines)
        case .anyPointer:
            let pointerKind = try type.anyPointerKind
            let statement: String
            switch pointerKind {
            case .struct: statement = "try raw.anyPointerField(at: \(offset)).setStruct(value)"
            case .list: statement = "try raw.anyPointerField(at: \(offset)).setList(value)"
            default: statement = "try raw.anyPointerField(at: \(offset)).set(value)"
            }
            try emitSetter(
                signature: "\(method)(_ value: \(swift))", selection: selection,
                indent: indent, statement: statement, into: &lines)
            lines.append(
                "\(indent)public var \(swiftIdentifier(originalName)): AnyPointerBuilder { get throws { try raw.anyPointerField(at: \(offset)) } }"
            )
        case .interface:
            lines.append("\(indent)public func \(method)(_ value: \(swift)) throws {")
            lines.append(
                "\(indent)    guard let tableIndex = value.raw.tableIndex else { throw CapabilityError.unserializableCapability }"
            )
            if let selection { lines.append(selection) }
            lines.append(
                "\(indent)    try raw.setCapabilityField(at: \(offset), tableIndex: tableIndex)"
            )
            lines.append("\(indent)}")
        default:
            break
        }
    }

    private func emitSetter(
        signature: String, selection: String?, indent: String, statement: String,
        into lines: inout [String]
    ) throws {
        lines.append("\(indent)public func \(signature) throws {")
        if let selection { lines.append(selection) }
        lines.append("\(indent)    \(statement)")
        lines.append("\(indent)}")
    }

    private func emitListSetter(
        method: String, element: Schema.`Type`, offset: UInt32,
        nodes: [Schema.ID: Schema.Node], names: [Schema.ID: String], selection: String?,
        indent: String,
        into lines: inout [String]
    ) throws {
        switch try element.kind {
        case .unknown:
            return
        default:
            break
        }
        let valueType = try swiftType(element, names: names)
        lines.append("\(indent)public func \(method)(_ values: [\(valueType)]) throws {")
        if let selection { lines.append(selection) }
        try emitListInitializationAndFill(
            element: element, owner: "raw", fieldOffset: offset, values: "values", depth: 0,
            nodes: nodes, indent: indent + "    ", into: &lines)
        lines.append("\(indent)}")
    }

    private func emitListInitializationAndFill(
        element: Schema.`Type`, owner: String, fieldOffset: UInt32?, values: String, depth: Int,
        nodes: [Schema.ID: Schema.Node], indent: String, into lines: inout [String]
    ) throws {
        let list = "list\(depth)"
        let initializer: String
        if try element.kind == .struct {
            let size = try structSize(element, nodes: nodes)
            if let fieldOffset {
                initializer =
                    "try \(owner).initStructListField(at: \(fieldOffset), count: \(values).count, dataWords: \(size.0), pointerCount: \(size.1))"
            } else {
                initializer = "try \(owner)"
            }
        } else if let fieldOffset {
            initializer =
                "try \(owner).initListField(at: \(fieldOffset), elementSize: \(try listElementSize(element)), count: \(values).count)"
        } else {
            initializer = "try \(owner)"
        }
        if try element.kind == .void {
            lines.append("\(indent)_ = \(initializer)")
            return
        }
        lines.append("\(indent)let \(list) = \(initializer)")
        switch try element.kind {
        case .struct:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list)[index].copyContent(from: value.raw) }"
            )
        case .bool:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setBool(at: index, to: value) }"
            )
        case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setInteger(at: index, to: value) }"
            )
        case .float32:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setFloat32(at: index, to: value) }"
            )
        case .float64:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setFloat64(at: index, to: value) }"
            )
        case .enum:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setInteger(at: index, to: value.rawValue) }"
            )
        case .text:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setText(at: index, to: value) }"
            )
        case .data:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).setData(at: index, to: value) }"
            )
        case .anyPointer:
            lines.append(
                "\(indent)for (index, value) in \(values).enumerated() { try \(list).anyPointer(at: index).set(value) }"
            )
        case .interface:
            lines.append("\(indent)for (index, value) in \(values).enumerated() {")
            lines.append(
                "\(indent)    guard let tableIndex = value.raw.tableIndex else { throw CapabilityError.unserializableCapability }"
            )
            lines.append(
                "\(indent)    try \(list).setCapability(at: index, tableIndex: tableIndex)"
            )
            lines.append("\(indent)}")
        case .list:
            let child = try element.elementType
            lines.append("\(indent)for (index, value) in \(values).enumerated() {")
            let childInit: String
            if try child.kind == .struct {
                let size = try structSize(child, nodes: nodes)
                childInit =
                    "\(list).initStructList(at: index, count: value.count, dataWords: \(size.0), pointerCount: \(size.1))"
            } else {
                childInit =
                    "\(list).initList(at: index, elementSize: \(try listElementSize(child)), count: value.count)"
            }
            try emitListInitializationAndFill(
                element: child, owner: childInit, fieldOffset: nil, values: "value",
                depth: depth + 1, nodes: nodes, indent: indent + "    ", into: &lines)
            lines.append("\(indent)}")
        default: break
        }
    }

    private func emitConstant(
        _ node: Schema.Node, name: String, names: [Schema.ID: String], indent: String,
        into lines: inout [String]
    ) throws {
        let type = try node.constantType
        let value = try node.constantValue
        let staticPrefix = indent.isEmpty ? "" : "static "
        switch try type.kind {
        case .struct:
            let bytes = try pointerValueBytes(value, type: type)
            lines.append(
                "\(indent)public \(staticPrefix)var \(name): \(try swiftType(type, names: names)) {"
            )
            lines.append("\(indent)    get throws {")
            lines.append(
                "\(indent)        let frame = try MessageFraming.decodePrefix(\(byteArray(bytes)))"
            )
            lines.append(
                "\(indent)        return \(try swiftType(type, names: names))(try frame.reader().rootStruct())"
            )
            lines.append("\(indent)    }")
            lines.append("\(indent)}")
        case .list:
            let bytes = try pointerValueBytes(value, type: type)
            lines.append(
                "\(indent)public \(staticPrefix)var \(name): \(try swiftType(type, names: names)) {"
            )
            lines.append("\(indent)    get throws {")
            lines.append(
                "\(indent)        let list = try MessageFraming.decodePrefix(\(byteArray(bytes))).reader().rootList()"
            )
            lines.append(
                "\(indent)        return \(try listRead(type.elementType, list: "list", names: names, depth: 0))"
            )
            lines.append("\(indent)    }")
            lines.append("\(indent)}")
        default:
            let storage = indent.isEmpty ? "let" : "static let"
            lines.append(
                "\(indent)public \(storage) \(name): \(try swiftType(type, names: names)) = \(try valueLiteral(value, type: type, names: names))"
            )
        }
        lines.append("")
    }
}

private func pointerValueBytes(_ value: Schema.Value, type: Schema.`Type`) throws -> [UInt8] {
    let message = try MessageBuilder(firstSegmentWords: 4096, allocationStrategy: .fixedSize)
    switch try type.kind {
    case .struct: _ = try message.setRoot(copying: value.structValue)
    case .list: try message.setRoot(copying: value.listValue)
    default: throw SwiftGeneratorError.unsupportedSchema("pointer constant \(try type.kind)")
    }
    return try message.framedBytes
}

private func byteArray(_ bytes: [UInt8]) -> String {
    "[" + bytes.map(String.init).joined(separator: ", ") + "]"
}

private func buildNames(nodes: [Schema.ID: Schema.Node]) throws -> [Schema.ID: String] {
    var result = [Schema.ID: String]()
    func visit(_ node: Schema.Node, prefix: String) throws {
        for nested in try node.nestedNodes {
            let id = try nested.id
            // Compiler requests may omit unused declarations from imported
            // files even though the imported file's nested-node table names them.
            guard let child = nodes[id] else { continue }
            let component = swiftIdentifier(try nested.name)
            let name = prefix.isEmpty ? component : prefix + "." + component
            result[id] = name
            try visit(child, prefix: name)
        }
        if try node.kind == .struct {
            for field in try node.fields where try field.kind == .group {
                let id = try field.groupTypeID
                guard let child = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
                let component = try groupName(field)
                let name = prefix.isEmpty ? component : prefix + "." + component
                result[id] = name
                try visit(child, prefix: name)
            }
        }
        if try node.kind == .interface {
            for method in try node.methods {
                let base = upperFirst(try method.name)
                for (id, suffix) in [
                    (try method.paramStructType, "Params"),
                    (try method.resultStructType, "Results"),
                ] {
                    guard result[id] == nil, let child = nodes[id], try child.scopeID == 0 else {
                        continue
                    }
                    let component = swiftIdentifier(base + suffix)
                    let name = prefix.isEmpty ? component : prefix + "." + component
                    result[id] = name
                    try visit(child, prefix: name)
                }
            }
        }
    }
    for node in nodes.values where try node.kind == .file {
        try visit(node, prefix: "")
    }
    return result
}

private func methodTypeName(_ id: Schema.ID, names: [Schema.ID: String]) throws -> String {
    guard let name = names[id] else { throw SwiftGeneratorError.missingNode(id) }
    return name
}

private func fileNeedsRPC(_ file: Schema.Node, nodes: [Schema.ID: Schema.Node]) throws -> Bool {
    func typeNeedsRPC(_ type: Schema.`Type`) throws -> Bool {
        if try type.kind == .interface { return true }
        if try type.kind == .list { return try typeNeedsRPC(type.elementType) }
        return false
    }

    func declarationNeedsRPC(_ node: Schema.Node) throws -> Bool {
        if try node.kind == .interface { return true }
        if try node.kind == .struct {
            for field in try node.fields {
                switch try field.kind {
                case .slot:
                    if try typeNeedsRPC(field.type) { return true }
                case .group:
                    guard let group = nodes[try field.groupTypeID] else {
                        throw SwiftGeneratorError.missingNode(try field.groupTypeID)
                    }
                    if try declarationNeedsRPC(group) { return true }
                case .unknown: break
                }
            }
        }
        for nested in try node.nestedNodes {
            if let child = nodes[try nested.id], try declarationNeedsRPC(child) { return true }
        }
        return false
    }

    return try declarationNeedsRPC(file)
}

private struct UnionStorage {
    var byteRanges = Set<Range<Int>>()
    var bitOffsets = Set<Int>()
    var pointerIndices = Set<Int>()
}

private func unionStorage(
    _ node: Schema.Node, nodes: [Schema.ID: Schema.Node]
) throws -> UnionStorage {
    var result = UnionStorage()
    for field in try node.fields
    where try field.discriminantValue != Schema.Field.noDiscriminant {
        try collectStorage(field, nodes: nodes, into: &result)
    }
    return result
}

private func collectStorage(
    _ field: Schema.Field, nodes: [Schema.ID: Schema.Node], into result: inout UnionStorage
) throws {
    switch try field.kind {
    case .slot:
        let type = try field.type
        let offset = try field.offset
        if isPointer(try type.kind) {
            result.pointerIndices.insert(Int(offset))
        } else {
            switch try type.kind {
            case .void: break
            case .bool: result.bitOffsets.insert(Int(offset))
            default:
                let start = Int(try byteOffset(type, offset))
                let width: Int
                switch try type.kind {
                case .int8, .uint8: width = 1
                case .int16, .uint16, .enum: width = 2
                case .int32, .uint32, .float32: width = 4
                case .int64, .uint64, .float64: width = 8
                default: width = 0
                }
                if width > 0 { result.byteRanges.insert(start..<(start + width)) }
            }
        }
    case .group:
        let id = try field.groupTypeID
        guard let group = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
        if try group.discriminantCount > 0 {
            let start = Int(try group.discriminantOffset) * 2
            result.byteRanges.insert(start..<(start + 2))
        }
        for child in try group.fields {
            try collectStorage(child, nodes: nodes, into: &result)
        }
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("field discriminant \(value)")
    }
}

private func unionSelection(
    field: Schema.Field, node: Schema.Node, storage: UnionStorage, indent: String
) throws -> String {
    let ranges = storage.byteRanges.sorted {
        ($0.lowerBound, $0.upperBound) < ($1.lowerBound, $1.upperBound)
    }.map { "\($0.lowerBound)..<\($0.upperBound)" }.joined(separator: ", ")
    let bits = storage.bitOffsets.sorted().map(String.init).joined(separator: ", ")
    let pointers = storage.pointerIndices.sorted().map(String.init).joined(separator: ", ")
    return
        "\(indent)try raw.selectUnion(discriminant: \(try field.discriminantValue), atByte: \(try node.discriminantOffset * 2), clearingData: [\(ranges)], clearingBits: [\(bits)], clearingPointers: [\(pointers)])"
}

private func groupName(_ field: Schema.Field) throws -> String {
    swiftIdentifier(upperFirst(try field.name))
}

private func parameterIndex(_ field: Schema.Field, scopeID: Schema.ID) throws -> Int? {
    guard try field.kind == .slot else { return nil }
    let type = try field.type
    guard try type.kind == .anyPointer else { return nil }
    if case .parameter(let parameterScope, let index) = try type.anyPointerKind,
        parameterScope == scopeID
    {
        return Int(index)
    }
    return nil
}

private func swiftType(_ type: Schema.`Type`, names: [Schema.ID: String]) throws -> String {
    switch try type.kind {
    case .void: return "Void"
    case .bool: return "Bool"
    case .int8: return "Int8"
    case .int16: return "Int16"
    case .int32: return "Int32"
    case .int64: return "Int64"
    case .uint8: return "UInt8"
    case .uint16: return "UInt16"
    case .uint32: return "UInt32"
    case .uint64: return "UInt64"
    case .float32: return "Float"
    case .float64: return "Double"
    case .text: return "String"
    case .data: return "[UInt8]"
    case .list: return "[\(try swiftType(type.elementType, names: names))]"
    case .enum: return try schemaName(type, names: names)
    case .struct: return try schemaName(type, names: names) + ".Reader"
    case .interface: return try schemaName(type, names: names) + ".Client"
    case .anyPointer:
        switch try type.anyPointerKind {
        case .struct: return "StructReader"
        case .list: return "ListReader"
        default: return "AnyPointerReader"
        }
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("type discriminant \(value)")
    }
}

private func readExpression(
    _ type: Schema.`Type`, field: Schema.Field, offset: UInt32, names: [Schema.ID: String]
) throws -> String {
    switch try type.kind {
    case .void: return "return ()"
    case .bool:
        return
            "return try raw.bool(atBit: \(offset), default: \(try defaultLiteral(field, names: names)))"
    case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
        return
            "return try raw.integer(atByte: \(try byteOffset(type, offset)), default: \(try defaultLiteral(field, names: names)))"
    case .float32:
        return
            "return try raw.float32(atByte: \(offset * 4), default: \(try defaultLiteral(field, names: names)))"
    case .float64:
        return
            "return try raw.float64(atByte: \(offset * 8), default: \(try defaultLiteral(field, names: names)))"
    case .text:
        let fallback = try defaultLiteral(field, names: names)
        return
            "return try raw.hasPointer(at: \(offset)) ? _capnpRequiredText(raw.textField(at: \(offset))) : \(fallback)"
    case .data:
        let fallback = try defaultLiteral(field, names: names)
        return
            "return try raw.hasPointer(at: \(offset)) ? raw.dataField(at: \(offset)).bytes : \(fallback)"
    case .enum:
        return
            "return \(try swiftType(type, names: names))(rawValue: try raw.integer(atByte: \(offset * 2), default: \(try field.defaultValue.enumValue)))"
    case .struct:
        let bytes = try pointerValueBytes(field.defaultValue, type: type)
        return
            "if try raw.hasPointer(at: \(offset)) { return \(try swiftType(type, names: names))(try raw.structField(at: \(offset))) }; let frame = try MessageFraming.decodePrefix(\(byteArray(bytes))); return \(try swiftType(type, names: names))(try frame.reader().rootStruct())"
    case .list:
        let bytes = try pointerValueBytes(field.defaultValue, type: type)
        return
            "let list = try raw.hasPointer(at: \(offset)) ? raw.listField(at: \(offset)) : MessageFraming.decodePrefix(\(byteArray(bytes))).reader().rootList(); return \(try listRead(type.elementType, list: "list", names: names, depth: 0))"
    case .anyPointer:
        switch try type.anyPointerKind {
        case .struct: return "return try raw.anyPointerField(at: \(offset)).asStruct()"
        case .list: return "return try raw.anyPointerField(at: \(offset)).asList()"
        default: return "return try raw.anyPointerField(at: \(offset))"
        }
    case .interface:
        return "return \(try swiftType(type, names: names))(try raw.anyPointerField(at: \(offset)))"
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("type discriminant \(value)")
    }
}

private func listRead(
    _ type: Schema.`Type`, list: String, names: [Schema.ID: String], depth: Int
) throws -> String {
    let index = "index\(depth)"
    switch try type.kind {
    case .void: return "Array(repeating: (), count: \(list).count)"
    case .bool: return "try (0..<\(list).count).map { try \(list).bool(at: $0) }"
    case .int8, .int16, .int32, .int64, .uint8, .uint16, .uint32, .uint64:
        return
            "try (0..<\(list).count).map { try \(list).integer(at: $0, as: \(try swiftType(type, names: names)).self) }"
    case .float32: return "try (0..<\(list).count).map { try \(list).float32(at: $0) }"
    case .float64: return "try (0..<\(list).count).map { try \(list).float64(at: $0) }"
    case .text:
        return
            "try (0..<\(list).count).map { try _capnpRequiredText(\(list).textPointerElement(at: $0)) }"
    case .data:
        return "try (0..<\(list).count).map { try \(list).dataPointerElement(at: $0).bytes }"
    case .enum:
        return
            "try (0..<\(list).count).map { \(try swiftType(type, names: names))(rawValue: try \(list).integer(at: $0, as: UInt16.self)) }"
    case .struct:
        return
            "try (0..<\(list).count).map { \(try swiftType(type, names: names))(try \(list).structElement(at: $0)) }"
    case .list:
        let child = "list\(depth + 1)"
        return
            "try (0..<\(list).count).map { \(index) in let \(child) = try \(list).pointerElement(at: \(index)); return \(try listRead(type.elementType, list: child, names: names, depth: depth + 1)) }"
    case .anyPointer:
        return "try (0..<\(list).count).map { try \(list).anyPointerElement(at: $0) }"
    case .interface:
        return
            "try (0..<\(list).count).map { \(try swiftType(type, names: names))(try \(list).anyPointerElement(at: $0)) }"
    default:
        throw SwiftGeneratorError.unsupportedSchema("list element \(try type.kind)")
    }
}

private func defaultLiteral(_ field: Schema.Field, names: [Schema.ID: String]) throws -> String {
    try valueLiteral(field.defaultValue, type: field.type, names: names)
}

private func valueLiteral(
    _ value: Schema.Value, type: Schema.`Type`, names: [Schema.ID: String]
) throws -> String {
    switch try type.kind {
    case .void: return "()"
    case .bool: return try value.boolValue ? "true" : "false"
    case .int8: return "Int8(\(try value.int8Value))"
    case .int16: return "Int16(\(try value.int16Value))"
    case .int32: return "Int32(\(try value.int32Value))"
    case .int64: return "Int64(\(try value.int64Value))"
    case .uint8: return "UInt8(\(try value.uint8Value))"
    case .uint16: return "UInt16(\(try value.uint16Value))"
    case .uint32: return "UInt32(\(try value.uint32Value))"
    case .uint64: return "UInt64(\(try value.uint64Value))"
    case .float32: return floatLiteral(Double(try value.float32Value), swiftType: "Float")
    case .float64: return floatLiteral(try value.float64Value, swiftType: "Double")
    case .text: return String(reflecting: try value.textValue)
    case .data: return "[" + (try value.dataValue).map(String.init).joined(separator: ", ") + "]"
    case .enum:
        return "\(try swiftType(type, names: names))(rawValue: \(try value.enumValue))"
    default:
        throw SwiftGeneratorError.unsupportedSchema("constant/default \(try type.kind)")
    }
}

private func floatLiteral(_ value: Double, swiftType: String) -> String {
    if value.isNaN { return "\(swiftType).nan" }
    if value == .infinity { return "\(swiftType).infinity" }
    if value == -.infinity { return "-\(swiftType).infinity" }
    return "\(swiftType)(\(value))"
}

private func byteOffset(_ type: Schema.`Type`, _ offset: UInt32) throws -> UInt32 {
    let width: UInt32
    switch try type.kind {
    case .int8, .uint8: width = 1
    case .int16, .uint16, .enum: width = 2
    case .int32, .uint32, .float32: width = 4
    case .int64, .uint64, .float64: width = 8
    default: throw SwiftGeneratorError.unsupportedSchema("data offset for \(try type.kind)")
    }
    return offset * width
}

private func listElementSize(_ type: Schema.`Type`) throws -> String {
    switch try type.kind {
    case .void: return ".void"
    case .bool: return ".bit"
    case .int8, .uint8: return ".byte"
    case .int16, .uint16, .enum: return ".twoBytes"
    case .int32, .uint32, .float32: return ".fourBytes"
    case .int64, .uint64, .float64: return ".eightBytes"
    case .text, .data, .list, .struct, .interface, .anyPointer: return ".pointer"
    case .unknown(let value):
        throw SwiftGeneratorError.unsupportedSchema("list element discriminant \(value)")
    }
}

private func structSize(
    _ type: Schema.`Type`, nodes: [Schema.ID: Schema.Node]
) throws -> (UInt16, UInt16) {
    let id = try type.typeID
    guard let node = nodes[id] else { throw SwiftGeneratorError.missingNode(id) }
    return try (node.dataWordCount, node.pointerCount)
}

private func schemaName(_ type: Schema.`Type`, names: [Schema.ID: String]) throws -> String {
    let id = try type.typeID
    guard let name = names[id] else { throw SwiftGeneratorError.missingNode(id) }
    return name
}

private func isPointer(_ kind: Schema.TypeKind) -> Bool {
    switch kind {
    case .text, .data, .list, .struct, .interface, .anyPointer: return true
    default: return false
    }
}

private func upperFirst(_ value: String) -> String {
    guard let first = value.first else { return value }
    return String(first).uppercased() + value.dropFirst()
}

public func swiftIdentifier(_ source: String) -> String {
    if source == "Type" { return "Type_" }
    return swiftKeywords.contains(source) ? "`\(source)`" : source
}

private func outputPath(for source: String) throws -> String {
    guard !source.isEmpty, !source.hasPrefix("/"), !source.split(separator: "/").contains("..")
    else {
        throw SwiftGeneratorError.invalidOutputPath(source)
    }
    return source + ".swift"
}

private func hex(_ value: UInt64) -> String {
    "0x" + String(value, radix: 16)
}

private let swiftKeywords: Set<String> = [
    "Any", "Protocol", "Self", "Type", "actor", "as", "associatedtype", "associativity",
    "async", "await", "borrowing", "break", "case", "catch", "class", "consume",
    "consuming", "continue", "convenience", "copy", "default", "defer", "deinit", "didSet",
    "distributed", "do", "dynamic", "else", "enum", "extension", "fallthrough", "false",
    "fileprivate", "final", "for", "func", "get", "guard", "if", "import", "indirect",
    "infix", "init", "inout", "internal", "is", "isolated", "lazy", "left", "let",
    "macro", "mutating", "nil", "nonisolated", "nonmutating", "open", "operator",
    "optional", "override", "package", "postfix", "precedence", "precedencegroup", "prefix",
    "private", "protocol", "public", "repeat", "required", "rethrows", "return", "right",
    "safe", "self", "set", "some", "static", "struct", "subscript", "super", "switch",
    "throws", "true", "try", "typealias", "unowned", "unsafe", "var", "weak", "where",
    "while", "willSet",
]
