// Generated by capnpc-swift. DO NOT EDIT.
// source: rpc-twoparty.capnp

import CapnProto

private func _capnpRequiredText(_ value: TextReader) throws -> String {
    guard let string = value.string else { throw CapnProtoError.invalidText }
    return string
}

public struct Side: RawRepresentable, Equatable, Hashable, Sendable {
    public let rawValue: UInt16
    public init(rawValue: UInt16) { self.rawValue = rawValue }
    public static let server = Side(rawValue: 0)
    public static let client = Side(rawValue: 1)
}

public enum VatId {
    public static let schemaID: UInt64 = 15135349989283412622
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var side: Side {
            get throws {
                return Side(rawValue: try raw.integer(atByte: 0, default: 0))
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setSide(_ value: Side) throws {
            try raw.setInteger(atByte: 0, to: value.rawValue, default: Side(rawValue: 0).rawValue)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 0))
    }
}

public enum ProvisionId {
    public static let schemaID: UInt64 = 13298295899470141463
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var joinId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setJoinId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 0))
    }
}

public enum RecipientId {
    public static let schemaID: UInt64 = 9940440221562733249
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 0, pointerCount: 0))
    }
}

public enum ThirdPartyCapId {
    public static let schemaID: UInt64 = 13006195034640135581
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 0, pointerCount: 0))
    }
}

public enum JoinKeyPart {
    public static let schemaID: UInt64 = 10786842769591618179
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var joinId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var partCount: UInt16 {
            get throws {
                return try raw.integer(atByte: 4, default: UInt16(0))
            }
        }
        public var partNum: UInt16 {
            get throws {
                return try raw.integer(atByte: 6, default: UInt16(0))
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setJoinId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setPartCount(_ value: UInt16) throws {
            try raw.setInteger(atByte: 4, to: value, default: UInt16(0))
        }
        public func setPartNum(_ value: UInt16) throws {
            try raw.setInteger(atByte: 6, to: value, default: UInt16(0))
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 0))
    }
}

public enum JoinResult {
    public static let schemaID: UInt64 = 11323802317489695726
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var joinId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var succeeded: Bool {
            get throws {
                return try raw.bool(atBit: 32, default: false)
            }
        }
        public var cap: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasCap: Bool { get throws { try raw.hasPointer(at: 0) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setJoinId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setSucceeded(_ value: Bool) throws {
            try raw.setBool(atBit: 32, to: value, default: false)
        }
        public func setCap(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 0).set(value)
        }
        public var cap: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 0) } }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}
