// Generated by capnpc-swift. DO NOT EDIT.
// source: rpc.capnp

import CapnProto

private func _capnpRequiredText(_ value: TextReader) throws -> String {
    guard let string = value.string else { throw CapnProtoError.invalidText }
    return string
}

public enum Message {
    public static let schemaID: UInt64 = 10500036013887172658
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }
    public enum Which {
        case unimplemented(Message.Reader)
        case abort(Exception.Reader)
        case call(Call.Reader)
        case `return`(Return.Reader)
        case finish(Finish.Reader)
        case resolve(Resolve.Reader)
        case release(Release.Reader)
        case obsoleteSave(AnyPointerReader)
        case bootstrap(Bootstrap.Reader)
        case obsoleteDelete(AnyPointerReader)
        case provide(Provide.Reader)
        case accept(Accept.Reader)
        case join(Join.Reader)
        case disembargo(Disembargo.Reader)
        case unknown(UInt16)
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var unimplemented: Message.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Message.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Message.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasUnimplemented: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var abort: Exception.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Exception.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Exception.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasAbort: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var call: Call.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Call.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Call.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasCall: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var `return`: Return.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Return.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Return.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasReturn: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var finish: Finish.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Finish.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Finish.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasFinish: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var resolve: Resolve.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Resolve.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Resolve.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasResolve: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var release: Release.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Release.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Release.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasRelease: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var obsoleteSave: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasObsoleteSave: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var bootstrap: Bootstrap.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Bootstrap.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Bootstrap.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasBootstrap: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var obsoleteDelete: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasObsoleteDelete: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var provide: Provide.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Provide.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Provide.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasProvide: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var accept: Accept.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Accept.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Accept.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasAccept: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var join: Join.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Join.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Join.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasJoin: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var disembargo: Disembargo.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return Disembargo.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Disembargo.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasDisembargo: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var which: Which {
            get throws {
                let tag = try raw.discriminant(atByte: 0)
                switch tag {
                case 0: return .unimplemented(try unimplemented)
                case 1: return .abort(try abort)
                case 2: return .call(try call)
                case 3: return .`return`(try `return`)
                case 4: return .finish(try finish)
                case 5: return .resolve(try resolve)
                case 6: return .release(try release)
                case 7: return .obsoleteSave(try obsoleteSave)
                case 8: return .bootstrap(try bootstrap)
                case 9: return .obsoleteDelete(try obsoleteDelete)
                case 10: return .provide(try provide)
                case 11: return .accept(try accept)
                case 12: return .join(try join)
                case 13: return .disembargo(try disembargo)
                default: return .unknown(tag)
                }
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setUnimplemented(_ value: Message.Reader) throws {
            try raw.selectUnion(
                discriminant: 0, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initUnimplemented() throws -> Message.Builder {
            try raw.selectUnion(
                discriminant: 0, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Message.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setAbort(_ value: Exception.Reader) throws {
            try raw.selectUnion(
                discriminant: 1, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initAbort() throws -> Exception.Builder {
            try raw.selectUnion(
                discriminant: 1, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Exception.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 2))
        }
        public func setCall(_ value: Call.Reader) throws {
            try raw.selectUnion(
                discriminant: 2, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initCall() throws -> Call.Builder {
            try raw.selectUnion(
                discriminant: 2, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Call.Builder(try raw.initStructField(at: 0, dataWords: 3, pointerCount: 3))
        }
        public func setReturn(_ value: Return.Reader) throws {
            try raw.selectUnion(
                discriminant: 3, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initReturn() throws -> Return.Builder {
            try raw.selectUnion(
                discriminant: 3, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Return.Builder(try raw.initStructField(at: 0, dataWords: 2, pointerCount: 1))
        }
        public func setFinish(_ value: Finish.Reader) throws {
            try raw.selectUnion(
                discriminant: 4, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initFinish() throws -> Finish.Builder {
            try raw.selectUnion(
                discriminant: 4, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Finish.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 0))
        }
        public func setResolve(_ value: Resolve.Reader) throws {
            try raw.selectUnion(
                discriminant: 5, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initResolve() throws -> Resolve.Builder {
            try raw.selectUnion(
                discriminant: 5, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Resolve.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setRelease(_ value: Release.Reader) throws {
            try raw.selectUnion(
                discriminant: 6, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initRelease() throws -> Release.Builder {
            try raw.selectUnion(
                discriminant: 6, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Release.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 0))
        }
        public func setObsoleteSave(_ value: AnyPointerReader) throws {
            try raw.selectUnion(
                discriminant: 7, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.anyPointerField(at: 0).set(value)
        }
        public var obsoleteSave: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 0) } }
        public func setBootstrap(_ value: Bootstrap.Reader) throws {
            try raw.selectUnion(
                discriminant: 8, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initBootstrap() throws -> Bootstrap.Builder {
            try raw.selectUnion(
                discriminant: 8, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Bootstrap.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setObsoleteDelete(_ value: AnyPointerReader) throws {
            try raw.selectUnion(
                discriminant: 9, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.anyPointerField(at: 0).set(value)
        }
        public var obsoleteDelete: AnyPointerBuilder {
            get throws { try raw.anyPointerField(at: 0) }
        }
        public func setProvide(_ value: Provide.Reader) throws {
            try raw.selectUnion(
                discriminant: 10, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initProvide() throws -> Provide.Builder {
            try raw.selectUnion(
                discriminant: 10, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Provide.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 2))
        }
        public func setAccept(_ value: Accept.Reader) throws {
            try raw.selectUnion(
                discriminant: 11, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initAccept() throws -> Accept.Builder {
            try raw.selectUnion(
                discriminant: 11, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Accept.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setJoin(_ value: Join.Reader) throws {
            try raw.selectUnion(
                discriminant: 12, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initJoin() throws -> Join.Builder {
            try raw.selectUnion(
                discriminant: 12, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Join.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 2))
        }
        public func setDisembargo(_ value: Disembargo.Reader) throws {
            try raw.selectUnion(
                discriminant: 13, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initDisembargo() throws -> Disembargo.Builder {
            try raw.selectUnion(
                discriminant: 13, atByte: 0, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Disembargo.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setUnknownDiscriminant(_ tag: UInt16) throws {
            try raw.setDiscriminant(atByte: 0, to: tag)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum Bootstrap {
    public static let schemaID: UInt64 = 16811039658553601732
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var deprecatedObjectId: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasDeprecatedObjectId: Bool { get throws { try raw.hasPointer(at: 0) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setDeprecatedObjectId(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 0).set(value)
        }
        public var deprecatedObjectId: AnyPointerBuilder {
            get throws { try raw.anyPointerField(at: 0) }
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum Call {
    public static let schemaID: UInt64 = 9469473312751832276
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var target: MessageTarget.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return MessageTarget.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return MessageTarget.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasTarget: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var interfaceId: UInt64 {
            get throws {
                return try raw.integer(atByte: 8, default: UInt64(0))
            }
        }
        public var methodId: UInt16 {
            get throws {
                return try raw.integer(atByte: 4, default: UInt16(0))
            }
        }
        public var params: Payload.Reader {
            get throws {
                if try raw.hasPointer(at: 1) { return Payload.Reader(try raw.structField(at: 1)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Payload.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasParams: Bool { get throws { try raw.hasPointer(at: 1) } }
        public var sendResultsTo: SendResultsTo.Reader { SendResultsTo.Reader(raw) }
        public var allowThirdPartyTailCall: Bool {
            get throws {
                return try raw.bool(atBit: 128, default: false)
            }
        }
        public var noPromisePipelining: Bool {
            get throws {
                return try raw.bool(atBit: 129, default: false)
            }
        }
        public var onlyPromisePipeline: Bool {
            get throws {
                return try raw.bool(atBit: 130, default: false)
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setTarget(_ value: MessageTarget.Reader) throws {
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initTarget() throws -> MessageTarget.Builder {
            return MessageTarget.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setInterfaceId(_ value: UInt64) throws {
            try raw.setInteger(atByte: 8, to: value, default: UInt64(0))
        }
        public func setMethodId(_ value: UInt16) throws {
            try raw.setInteger(atByte: 4, to: value, default: UInt16(0))
        }
        public func setParams(_ value: Payload.Reader) throws {
            try raw.setStructField(at: 1, copying: value.raw)
        }
        public func initParams() throws -> Payload.Builder {
            return Payload.Builder(try raw.initStructField(at: 1, dataWords: 0, pointerCount: 2))
        }
        public var sendResultsTo: SendResultsTo.Builder { SendResultsTo.Builder(raw) }
        public func setAllowThirdPartyTailCall(_ value: Bool) throws {
            try raw.setBool(atBit: 128, to: value, default: false)
        }
        public func setNoPromisePipelining(_ value: Bool) throws {
            try raw.setBool(atBit: 129, to: value, default: false)
        }
        public func setOnlyPromisePipeline(_ value: Bool) throws {
            try raw.setBool(atBit: 130, to: value, default: false)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 3, pointerCount: 3))
    }

    public enum SendResultsTo {
        public static let schemaID: UInt64 = 15774052265921044377
        public enum Which {
            case caller
            case yourself
            case thirdParty(AnyPointerReader)
            case unknown(UInt16)
        }

        public struct Reader {
            public let raw: StructReader
            public init(_ raw: StructReader) { self.raw = raw }
            public var caller: Void {
                get throws {
                    return ()
                }
            }
            public var yourself: Void {
                get throws {
                    return ()
                }
            }
            public var thirdParty: AnyPointerReader {
                get throws {
                    return try raw.anyPointerField(at: 2)
                }
            }
            public var hasThirdParty: Bool { get throws { try raw.hasPointer(at: 2) } }
            public var which: Which {
                get throws {
                    let tag = try raw.discriminant(atByte: 6)
                    switch tag {
                    case 0: return .caller
                    case 1: return .yourself
                    case 2: return .thirdParty(try thirdParty)
                    default: return .unknown(tag)
                    }
                }
            }
        }

        public struct Builder {
            public let raw: StructBuilder
            public init(_ raw: StructBuilder) { self.raw = raw }
            public func setCaller() throws {
                try raw.selectUnion(
                    discriminant: 0, atByte: 6, clearingData: [], clearingBits: [],
                    clearingPointers: [2])
            }
            public func setYourself() throws {
                try raw.selectUnion(
                    discriminant: 1, atByte: 6, clearingData: [], clearingBits: [],
                    clearingPointers: [2])
            }
            public func setThirdParty(_ value: AnyPointerReader) throws {
                try raw.selectUnion(
                    discriminant: 2, atByte: 6, clearingData: [], clearingBits: [],
                    clearingPointers: [2])
                try raw.anyPointerField(at: 2).set(value)
            }
            public var thirdParty: AnyPointerBuilder {
                get throws { try raw.anyPointerField(at: 2) }
            }
            public func setUnknownDiscriminant(_ tag: UInt16) throws {
                try raw.setDiscriminant(atByte: 6, to: tag)
            }
        }

    }

}

public enum Return {
    public static let schemaID: UInt64 = 11392333052105676602
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }
    public enum Which {
        case results(Payload.Reader)
        case exception(Exception.Reader)
        case canceled
        case resultsSentElsewhere
        case takeFromOtherQuestion(UInt32)
        case acceptFromThirdParty(AnyPointerReader)
        case unknown(UInt16)
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var answerId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var releaseParamCaps: Bool {
            get throws {
                return try raw.bool(atBit: 32, default: true)
            }
        }
        public var results: Payload.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Payload.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Payload.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasResults: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var exception: Exception.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Exception.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Exception.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasException: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var canceled: Void {
            get throws {
                return ()
            }
        }
        public var resultsSentElsewhere: Void {
            get throws {
                return ()
            }
        }
        public var takeFromOtherQuestion: UInt32 {
            get throws {
                return try raw.integer(atByte: 8, default: UInt32(0))
            }
        }
        public var acceptFromThirdParty: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasAcceptFromThirdParty: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var noFinishNeeded: Bool {
            get throws {
                return try raw.bool(atBit: 33, default: false)
            }
        }
        public var which: Which {
            get throws {
                let tag = try raw.discriminant(atByte: 6)
                switch tag {
                case 0: return .results(try results)
                case 1: return .exception(try exception)
                case 2: return .canceled
                case 3: return .resultsSentElsewhere
                case 4: return .takeFromOtherQuestion(try takeFromOtherQuestion)
                case 5: return .acceptFromThirdParty(try acceptFromThirdParty)
                default: return .unknown(tag)
                }
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setAnswerId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setReleaseParamCaps(_ value: Bool) throws {
            try raw.setBool(atBit: 32, to: value, default: true)
        }
        public func setResults(_ value: Payload.Reader) throws {
            try raw.selectUnion(
                discriminant: 0, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initResults() throws -> Payload.Builder {
            try raw.selectUnion(
                discriminant: 0, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
            return Payload.Builder(try raw.initStructField(at: 0, dataWords: 0, pointerCount: 2))
        }
        public func setException(_ value: Exception.Reader) throws {
            try raw.selectUnion(
                discriminant: 1, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initException() throws -> Exception.Builder {
            try raw.selectUnion(
                discriminant: 1, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
            return Exception.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 2))
        }
        public func setCanceled() throws {
            try raw.selectUnion(
                discriminant: 2, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
        }
        public func setResultsSentElsewhere() throws {
            try raw.selectUnion(
                discriminant: 3, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
        }
        public func setTakeFromOtherQuestion(_ value: UInt32) throws {
            try raw.selectUnion(
                discriminant: 4, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
            try raw.setInteger(atByte: 8, to: value, default: UInt32(0))
        }
        public func setAcceptFromThirdParty(_ value: AnyPointerReader) throws {
            try raw.selectUnion(
                discriminant: 5, atByte: 6, clearingData: [8..<12], clearingBits: [],
                clearingPointers: [0])
            try raw.anyPointerField(at: 0).set(value)
        }
        public var acceptFromThirdParty: AnyPointerBuilder {
            get throws { try raw.anyPointerField(at: 0) }
        }
        public func setNoFinishNeeded(_ value: Bool) throws {
            try raw.setBool(atBit: 33, to: value, default: false)
        }
        public func setUnknownDiscriminant(_ tag: UInt16) throws {
            try raw.setDiscriminant(atByte: 6, to: tag)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 2, pointerCount: 1))
    }
}

public enum Finish {
    public static let schemaID: UInt64 = 15239388059401719395
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var releaseResultCaps: Bool {
            get throws {
                return try raw.bool(atBit: 32, default: true)
            }
        }
        public var requireEarlyCancellationWorkaround: Bool {
            get throws {
                return try raw.bool(atBit: 33, default: true)
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setReleaseResultCaps(_ value: Bool) throws {
            try raw.setBool(atBit: 32, to: value, default: true)
        }
        public func setRequireEarlyCancellationWorkaround(_ value: Bool) throws {
            try raw.setBool(atBit: 33, to: value, default: true)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 0))
    }
}

public enum Resolve {
    public static let schemaID: UInt64 = 13529541526594062446
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }
    public enum Which {
        case cap(CapDescriptor.Reader)
        case exception(Exception.Reader)
        case unknown(UInt16)
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var promiseId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var cap: CapDescriptor.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return CapDescriptor.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return CapDescriptor.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasCap: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var exception: Exception.Reader {
            get throws {
                if try raw.hasPointer(at: 0) { return Exception.Reader(try raw.structField(at: 0)) };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return Exception.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasException: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var which: Which {
            get throws {
                let tag = try raw.discriminant(atByte: 4)
                switch tag {
                case 0: return .cap(try cap)
                case 1: return .exception(try exception)
                default: return .unknown(tag)
                }
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setPromiseId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setCap(_ value: CapDescriptor.Reader) throws {
            try raw.selectUnion(
                discriminant: 0, atByte: 4, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initCap() throws -> CapDescriptor.Builder {
            try raw.selectUnion(
                discriminant: 0, atByte: 4, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return CapDescriptor.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setException(_ value: Exception.Reader) throws {
            try raw.selectUnion(
                discriminant: 1, atByte: 4, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initException() throws -> Exception.Builder {
            try raw.selectUnion(
                discriminant: 1, atByte: 4, clearingData: [], clearingBits: [],
                clearingPointers: [0])
            return Exception.Builder(try raw.initStructField(at: 0, dataWords: 1, pointerCount: 2))
        }
        public func setUnknownDiscriminant(_ tag: UInt16) throws {
            try raw.setDiscriminant(atByte: 4, to: tag)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum Release {
    public static let schemaID: UInt64 = 12473400923157197975
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var id: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var referenceCount: UInt32 {
            get throws {
                return try raw.integer(atByte: 4, default: UInt32(0))
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setReferenceCount(_ value: UInt32) throws {
            try raw.setInteger(atByte: 4, to: value, default: UInt32(0))
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 0))
    }
}

public enum Disembargo {
    public static let schemaID: UInt64 = 17970548384007534353
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var target: MessageTarget.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return MessageTarget.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return MessageTarget.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasTarget: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var context: Context.Reader { Context.Reader(raw) }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setTarget(_ value: MessageTarget.Reader) throws {
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initTarget() throws -> MessageTarget.Builder {
            return MessageTarget.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public var context: Context.Builder { Context.Builder(raw) }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }

    public enum Context {
        public static let schemaID: UInt64 = 15376050949367520589
        public enum Which {
            case senderLoopback(UInt32)
            case receiverLoopback(UInt32)
            case accept
            case provide(UInt32)
            case unknown(UInt16)
        }

        public struct Reader {
            public let raw: StructReader
            public init(_ raw: StructReader) { self.raw = raw }
            public var senderLoopback: UInt32 {
                get throws {
                    return try raw.integer(atByte: 0, default: UInt32(0))
                }
            }
            public var receiverLoopback: UInt32 {
                get throws {
                    return try raw.integer(atByte: 0, default: UInt32(0))
                }
            }
            public var accept: Void {
                get throws {
                    return ()
                }
            }
            public var provide: UInt32 {
                get throws {
                    return try raw.integer(atByte: 0, default: UInt32(0))
                }
            }
            public var which: Which {
                get throws {
                    let tag = try raw.discriminant(atByte: 4)
                    switch tag {
                    case 0: return .senderLoopback(try senderLoopback)
                    case 1: return .receiverLoopback(try receiverLoopback)
                    case 2: return .accept
                    case 3: return .provide(try provide)
                    default: return .unknown(tag)
                    }
                }
            }
        }

        public struct Builder {
            public let raw: StructBuilder
            public init(_ raw: StructBuilder) { self.raw = raw }
            public func setSenderLoopback(_ value: UInt32) throws {
                try raw.selectUnion(
                    discriminant: 0, atByte: 4, clearingData: [0..<4], clearingBits: [],
                    clearingPointers: [])
                try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
            }
            public func setReceiverLoopback(_ value: UInt32) throws {
                try raw.selectUnion(
                    discriminant: 1, atByte: 4, clearingData: [0..<4], clearingBits: [],
                    clearingPointers: [])
                try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
            }
            public func setAccept() throws {
                try raw.selectUnion(
                    discriminant: 2, atByte: 4, clearingData: [0..<4], clearingBits: [],
                    clearingPointers: [])
            }
            public func setProvide(_ value: UInt32) throws {
                try raw.selectUnion(
                    discriminant: 3, atByte: 4, clearingData: [0..<4], clearingBits: [],
                    clearingPointers: [])
                try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
            }
            public func setUnknownDiscriminant(_ tag: UInt16) throws {
                try raw.setDiscriminant(atByte: 4, to: tag)
            }
        }

    }

}

public enum Provide {
    public static let schemaID: UInt64 = 11270825879279873114
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var target: MessageTarget.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return MessageTarget.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return MessageTarget.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasTarget: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var recipient: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 1)
            }
        }
        public var hasRecipient: Bool { get throws { try raw.hasPointer(at: 1) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setTarget(_ value: MessageTarget.Reader) throws {
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initTarget() throws -> MessageTarget.Builder {
            return MessageTarget.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setRecipient(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 1).set(value)
        }
        public var recipient: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 1) } }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 2))
    }
}

public enum Accept {
    public static let schemaID: UInt64 = 15332985841292492822
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var provision: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasProvision: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var embargo: Bool {
            get throws {
                return try raw.bool(atBit: 32, default: false)
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setProvision(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 0).set(value)
        }
        public var provision: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 0) } }
        public func setEmbargo(_ value: Bool) throws {
            try raw.setBool(atBit: 32, to: value, default: false)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum Join {
    public static let schemaID: UInt64 = 18149955118657700271
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var target: MessageTarget.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return MessageTarget.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return MessageTarget.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasTarget: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var keyPart: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 1)
            }
        }
        public var hasKeyPart: Bool { get throws { try raw.hasPointer(at: 1) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setTarget(_ value: MessageTarget.Reader) throws {
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initTarget() throws -> MessageTarget.Builder {
            return MessageTarget.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setKeyPart(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 1).set(value)
        }
        public var keyPart: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 1) } }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 2))
    }
}

public enum MessageTarget {
    public static let schemaID: UInt64 = 10789521159760378817
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }
    public enum Which {
        case importedCap(UInt32)
        case promisedAnswer(PromisedAnswer.Reader)
        case unknown(UInt16)
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var importedCap: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var promisedAnswer: PromisedAnswer.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return PromisedAnswer.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return PromisedAnswer.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasPromisedAnswer: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var which: Which {
            get throws {
                let tag = try raw.discriminant(atByte: 4)
                switch tag {
                case 0: return .importedCap(try importedCap)
                case 1: return .promisedAnswer(try promisedAnswer)
                default: return .unknown(tag)
                }
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setImportedCap(_ value: UInt32) throws {
            try raw.selectUnion(
                discriminant: 0, atByte: 4, clearingData: [0..<4], clearingBits: [],
                clearingPointers: [0])
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func setPromisedAnswer(_ value: PromisedAnswer.Reader) throws {
            try raw.selectUnion(
                discriminant: 1, atByte: 4, clearingData: [0..<4], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initPromisedAnswer() throws -> PromisedAnswer.Builder {
            try raw.selectUnion(
                discriminant: 1, atByte: 4, clearingData: [0..<4], clearingBits: [],
                clearingPointers: [0])
            return PromisedAnswer.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setUnknownDiscriminant(_ tag: UInt16) throws {
            try raw.setDiscriminant(atByte: 4, to: tag)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum Payload {
    public static let schemaID: UInt64 = 11100916931204903995
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var content: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasContent: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var capTable: [CapDescriptor.Reader] {
            get throws {
                let list =
                    try raw.hasPointer(at: 1)
                    ? raw.listField(at: 1)
                    : MessageFraming.decodePrefix([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])
                        .reader().rootList();
                return try (0..<list.count).map {
                    CapDescriptor.Reader(try list.structElement(at: $0))
                }
            }
        }
        public var hasCapTable: Bool { get throws { try raw.hasPointer(at: 1) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setContent(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 0).set(value)
        }
        public var content: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 0) } }
        public func initCapTable(count: Int) throws -> StructListBuilder {
            return try raw.initStructListField(at: 1, count: count, dataWords: 1, pointerCount: 1)
        }
        public func setCapTable(_ values: [CapDescriptor.Reader]) throws {
            let list0 = try raw.initStructListField(
                at: 1, count: values.count, dataWords: 1, pointerCount: 1)
            for (index, value) in values.enumerated() {
                try list0[index].copyContent(from: value.raw)
            }
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 0, pointerCount: 2))
    }
}

public enum CapDescriptor {
    public static let schemaID: UInt64 = 9593755465305995440
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }
    public enum Which {
        case none
        case senderHosted(UInt32)
        case senderPromise(UInt32)
        case receiverHosted(UInt32)
        case receiverAnswer(PromisedAnswer.Reader)
        case thirdPartyHosted(ThirdPartyCapDescriptor.Reader)
        case unknown(UInt16)
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var none: Void {
            get throws {
                return ()
            }
        }
        public var senderHosted: UInt32 {
            get throws {
                return try raw.integer(atByte: 4, default: UInt32(0))
            }
        }
        public var senderPromise: UInt32 {
            get throws {
                return try raw.integer(atByte: 4, default: UInt32(0))
            }
        }
        public var receiverHosted: UInt32 {
            get throws {
                return try raw.integer(atByte: 4, default: UInt32(0))
            }
        }
        public var receiverAnswer: PromisedAnswer.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return PromisedAnswer.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return PromisedAnswer.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasReceiverAnswer: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var thirdPartyHosted: ThirdPartyCapDescriptor.Reader {
            get throws {
                if try raw.hasPointer(at: 0) {
                    return ThirdPartyCapDescriptor.Reader(try raw.structField(at: 0))
                };
                let frame = try MessageFraming.decodePrefix([
                    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                ]); return ThirdPartyCapDescriptor.Reader(try frame.reader().rootStruct())
            }
        }
        public var hasThirdPartyHosted: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var attachedFd: UInt8 {
            get throws {
                return try raw.integer(atByte: 2, default: UInt8(255))
            }
        }
        public var which: Which {
            get throws {
                let tag = try raw.discriminant(atByte: 0)
                switch tag {
                case 0: return .none
                case 1: return .senderHosted(try senderHosted)
                case 2: return .senderPromise(try senderPromise)
                case 3: return .receiverHosted(try receiverHosted)
                case 4: return .receiverAnswer(try receiverAnswer)
                case 5: return .thirdPartyHosted(try thirdPartyHosted)
                default: return .unknown(tag)
                }
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setNone() throws {
            try raw.selectUnion(
                discriminant: 0, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
        }
        public func setSenderHosted(_ value: UInt32) throws {
            try raw.selectUnion(
                discriminant: 1, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            try raw.setInteger(atByte: 4, to: value, default: UInt32(0))
        }
        public func setSenderPromise(_ value: UInt32) throws {
            try raw.selectUnion(
                discriminant: 2, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            try raw.setInteger(atByte: 4, to: value, default: UInt32(0))
        }
        public func setReceiverHosted(_ value: UInt32) throws {
            try raw.selectUnion(
                discriminant: 3, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            try raw.setInteger(atByte: 4, to: value, default: UInt32(0))
        }
        public func setReceiverAnswer(_ value: PromisedAnswer.Reader) throws {
            try raw.selectUnion(
                discriminant: 4, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initReceiverAnswer() throws -> PromisedAnswer.Builder {
            try raw.selectUnion(
                discriminant: 4, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            return PromisedAnswer.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setThirdPartyHosted(_ value: ThirdPartyCapDescriptor.Reader) throws {
            try raw.selectUnion(
                discriminant: 5, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            try raw.setStructField(at: 0, copying: value.raw)
        }
        public func initThirdPartyHosted() throws -> ThirdPartyCapDescriptor.Builder {
            try raw.selectUnion(
                discriminant: 5, atByte: 0, clearingData: [4..<8], clearingBits: [],
                clearingPointers: [0])
            return ThirdPartyCapDescriptor.Builder(
                try raw.initStructField(at: 0, dataWords: 1, pointerCount: 1))
        }
        public func setAttachedFd(_ value: UInt8) throws {
            try raw.setInteger(atByte: 2, to: value, default: UInt8(255))
        }
        public func setUnknownDiscriminant(_ tag: UInt16) throws {
            try raw.setDiscriminant(atByte: 0, to: tag)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum PromisedAnswer {
    public static let schemaID: UInt64 = 15564635848320162976
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var questionId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
        public var transform: [PromisedAnswer.Op.Reader] {
            get throws {
                let list =
                    try raw.hasPointer(at: 0)
                    ? raw.listField(at: 0)
                    : MessageFraming.decodePrefix([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])
                        .reader().rootList();
                return try (0..<list.count).map {
                    PromisedAnswer.Op.Reader(try list.structElement(at: $0))
                }
            }
        }
        public var hasTransform: Bool { get throws { try raw.hasPointer(at: 0) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setQuestionId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
        public func initTransform(count: Int) throws -> StructListBuilder {
            return try raw.initStructListField(at: 0, count: count, dataWords: 1, pointerCount: 0)
        }
        public func setTransform(_ values: [PromisedAnswer.Op.Reader]) throws {
            let list0 = try raw.initStructListField(
                at: 0, count: values.count, dataWords: 1, pointerCount: 0)
            for (index, value) in values.enumerated() {
                try list0[index].copyContent(from: value.raw)
            }
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }

    public enum Op {
        public static let schemaID: UInt64 = 17516350820840804481
        public enum Pointer: CapnProtoPointerType {
            public static func read(from pointer: AnyPointerReader) throws -> Reader {
                Reader(try pointer.asStruct())
            }
            public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
                try pointer.setStruct(value.raw)
            }
        }
        public enum Which {
            case noop
            case getPointerField(UInt16)
            case unknown(UInt16)
        }

        public struct Reader {
            public let raw: StructReader
            public init(_ raw: StructReader) { self.raw = raw }
            public var noop: Void {
                get throws {
                    return ()
                }
            }
            public var getPointerField: UInt16 {
                get throws {
                    return try raw.integer(atByte: 2, default: UInt16(0))
                }
            }
            public var which: Which {
                get throws {
                    let tag = try raw.discriminant(atByte: 0)
                    switch tag {
                    case 0: return .noop
                    case 1: return .getPointerField(try getPointerField)
                    default: return .unknown(tag)
                    }
                }
            }
        }

        public struct Builder {
            public let raw: StructBuilder
            public init(_ raw: StructBuilder) { self.raw = raw }
            public func setNoop() throws {
                try raw.selectUnion(
                    discriminant: 0, atByte: 0, clearingData: [2..<4], clearingBits: [],
                    clearingPointers: [])
            }
            public func setGetPointerField(_ value: UInt16) throws {
                try raw.selectUnion(
                    discriminant: 1, atByte: 0, clearingData: [2..<4], clearingBits: [],
                    clearingPointers: [])
                try raw.setInteger(atByte: 2, to: value, default: UInt16(0))
            }
            public func setUnknownDiscriminant(_ tag: UInt16) throws {
                try raw.setDiscriminant(atByte: 0, to: tag)
            }
        }

        public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
            throws -> Reader
        {
            let frame = try MessageFraming.decodePrefix(bytes)
            guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
            return Reader(try frame.reader(options: options).rootStruct())
        }

        public static func initRoot(in message: MessageBuilder) throws -> Builder {
            Builder(try message.initRootStruct(dataWords: 1, pointerCount: 0))
        }
    }

}

public enum ThirdPartyCapDescriptor {
    public static let schemaID: UInt64 = 15235686326393111165
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var id: AnyPointerReader {
            get throws {
                return try raw.anyPointerField(at: 0)
            }
        }
        public var hasId: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var vineId: UInt32 {
            get throws {
                return try raw.integer(atByte: 0, default: UInt32(0))
            }
        }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setId(_ value: AnyPointerReader) throws {
            try raw.anyPointerField(at: 0).set(value)
        }
        public var id: AnyPointerBuilder { get throws { try raw.anyPointerField(at: 0) } }
        public func setVineId(_ value: UInt32) throws {
            try raw.setInteger(atByte: 0, to: value, default: UInt32(0))
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 1))
    }
}

public enum Exception {
    public static let schemaID: UInt64 = 15430940935639230746
    public enum Pointer: CapnProtoPointerType {
        public static func read(from pointer: AnyPointerReader) throws -> Reader {
            Reader(try pointer.asStruct())
        }
        public static func write(_ value: Reader, to pointer: AnyPointerBuilder) throws {
            try pointer.setStruct(value.raw)
        }
    }

    public struct Reader {
        public let raw: StructReader
        public init(_ raw: StructReader) { self.raw = raw }
        public var reason: String {
            get throws {
                return try raw.hasPointer(at: 0) ? _capnpRequiredText(raw.textField(at: 0)) : ""
            }
        }
        public var hasReason: Bool { get throws { try raw.hasPointer(at: 0) } }
        public var obsoleteIsCallersFault: Bool {
            get throws {
                return try raw.bool(atBit: 0, default: false)
            }
        }
        public var obsoleteDurability: UInt16 {
            get throws {
                return try raw.integer(atByte: 2, default: UInt16(0))
            }
        }
        public var type: Exception.Type_ {
            get throws {
                return Exception.Type_(rawValue: try raw.integer(atByte: 4, default: 0))
            }
        }
        public var trace: String {
            get throws {
                return try raw.hasPointer(at: 1) ? _capnpRequiredText(raw.textField(at: 1)) : ""
            }
        }
        public var hasTrace: Bool { get throws { try raw.hasPointer(at: 1) } }
    }

    public struct Builder {
        public let raw: StructBuilder
        public init(_ raw: StructBuilder) { self.raw = raw }
        public func setReason(_ value: String) throws {
            _ = try raw.setTextField(at: 0, to: value)
        }
        public func setObsoleteIsCallersFault(_ value: Bool) throws {
            try raw.setBool(atBit: 0, to: value, default: false)
        }
        public func setObsoleteDurability(_ value: UInt16) throws {
            try raw.setInteger(atByte: 2, to: value, default: UInt16(0))
        }
        public func setType(_ value: Exception.Type_) throws {
            try raw.setInteger(
                atByte: 4, to: value.rawValue, default: Exception.Type_(rawValue: 0).rawValue)
        }
        public func setTrace(_ value: String) throws {
            _ = try raw.setTextField(at: 1, to: value)
        }
    }

    public static func readRoot(from bytes: [UInt8], options: ReaderOptions = ReaderOptions())
        throws -> Reader
    {
        let frame = try MessageFraming.decodePrefix(bytes)
        guard frame.byteCount == bytes.count else { throw CapnProtoError.invalidFrame }
        return Reader(try frame.reader(options: options).rootStruct())
    }

    public static func initRoot(in message: MessageBuilder) throws -> Builder {
        Builder(try message.initRootStruct(dataWords: 1, pointerCount: 2))
    }

    public struct Type_: RawRepresentable, Equatable, Hashable, Sendable {
        public let rawValue: UInt16
        public init(rawValue: UInt16) { self.rawValue = rawValue }
        public static let failed = Type_(rawValue: 0)
        public static let overloaded = Type_(rawValue: 1)
        public static let disconnected = Type_(rawValue: 2)
        public static let unimplemented = Type_(rawValue: 3)
    }

}
